(()=>{'use strict';
const $=id=>document.getElementById(id);if(!window.THREE){$('startBtn').disabled=true;return}const THREE=window.THREE,qs=new URLSearchParams(location.search),raw=Number(qs.get('entry')),ENTRY=[1,5,20].includes(raw)?raw:1,STORAGE='skillArcadeDemoAccountV1',FEE=.05,FIXED=1/120;
const keys=new Set();let account=load(),wallet=account.wallet,state='menu',count=3,last=performance.now(),acc=0,elapsed=0,toastT=0,finished=false;
function load(){const f={wallet:25,totalPrizes:0,wins:0,totalMatches:0,matches:[]};try{const d=JSON.parse(localStorage.getItem(STORAGE)||'null');return d?{...f,...d,matches:Array.isArray(d.matches)?d.matches:[]}:f}catch{return f}}function save(){account.wallet=Math.max(0,wallet);localStorage.setItem(STORAGE,JSON.stringify(account))}function money(v){return `$${Math.max(0,+v||0).toFixed(2)}`}function signed(v){return `${v>=0?'+':'-'}$${Math.abs(v).toFixed(2)}`}function toast(s){$('toast').textContent=s;$('toast').classList.add('show');toastT=1.1}

const PLAYERS=12,PAYOUTS=[6,3.4,2].map(v=>v*ENTRY),POOL=PLAYERS*ENTRY*(1-FEE),names=['You','Nova','Mika','Rook','Volt','Pip','Zed','Kira','Atlas','Echo','Juno','Blaze'],colors=[0xffd84e,0xff5f83,0x55d6b0,0x53c8ff,0x9f7cff,0xff8a4f,0x77dd67,0x42d1d6,0xffb347,0xe66cff,0x6f8cff,0xff6b57];
let players=[],walls=[],wallTimer=0,wallCount=0,actionLatch=false,outSeq=0,activeMap=null;
const WALL_MAPS=[
{id:'meadow',name:'Meadow Run',sky:0x9fdcff,floor:0x74b56b,colors:[0xff826e,0x7d73ff],gaps:[-3.8,-1.8,.3,2.4,4.0,1.1,-2.8,3.2,-.7,4.2,-4.1,1.9]},
{id:'zigzag',name:'Zigzag Walls',sky:0xc7b6ff,floor:0x6d67a8,colors:[0x58d6c5,0xffc44d],gaps:[-4.0,4.0,-3.3,3.2,-2.5,2.4,-1.6,1.5,-.8,.8,-3.8,3.7]},
{id:'center',name:'Center Squeeze',sky:0xffd1ba,floor:0xa56d54,colors:[0xff6e9d,0x56c9ff],gaps:[0,1.2,-1.2,.5,-.5,2.3,-2.3,.2,-.2,3.4,-3.4,0]},
{id:'switch',name:'Switchback',sky:0xb8ead4,floor:0x5e9478,colors:[0xffd84e,0xb18cff],gaps:[3.7,2.2,.8,-1.0,-2.5,-3.8,-2.2,-.6,1.1,2.7,4.0,.2]}
];
function economy(){$('entryValue').textContent=money(ENTRY);$('poolValue').textContent=money(POOL);$('p1').textContent=money(PAYOUTS[0]);$('p2').textContent=money(PAYOUTS[1]);$('p3').textContent=money(PAYOUTS[2]);$('walletValue').textContent=$('lobbyWallet').textContent=money(wallet);$('startBtn').textContent=wallet>=ENTRY?`ENTER MATCH · ${money(ENTRY)}`:'INSUFFICIENT DEMO BALANCE';$('startBtn').disabled=wallet<ENTRY}
const renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.shadowMap.enabled=true;const scene=new THREE.Scene();scene.background=new THREE.Color(0x9fdcff);scene.fog=new THREE.Fog(0x9fdcff,28,70);const camera=new THREE.PerspectiveCamera(55,1,.05,100);scene.add(new THREE.HemisphereLight(0xffffff,0x58735b,1.8));const sun=new THREE.DirectionalLight(0xffffff,1.6);sun.position.set(-10,18,10);scene.add(sun);const world=new THREE.Group(),actors=new THREE.Group();scene.add(world,actors);const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.72});const floor=new THREE.Mesh(new THREE.BoxGeometry(17,.5,30),mat(0x74b56b));floor.position.set(0,-.3,1);world.add(floor);for(let x=-7.5;x<=7.5;x+=2.5){const stripe=new THREE.Mesh(new THREE.BoxGeometry(.05,.03,20),mat(0xdaf0d5));stripe.position.set(x,.01,2);world.add(stripe)}
function bean(i){return window.SkillArcadeCharacters?.make(THREE,i,{colors,scale:.98,markerRadius:.72,labelY:2.08})||new THREE.Group()}
function reset(){if(!activeMap||state==='result')activeMap=window.SkillArcadeMaps?.pick('wall-dodge',WALL_MAPS)||WALL_MAPS[0];scene.background.setHex(activeMap.sky);scene.fog.color.setHex(activeMap.sky);floor.material.color.setHex(activeMap.floor);actors.clear();players=[];walls.forEach(w=>world.remove(w.g));walls=[];wallTimer=.8;wallCount=0;outSeq=0;for(let i=0;i<PLAYERS;i++){const g=bean(i);actors.add(g);players.push({id:i,name:names[i],g,x:-6.6+(i%6)*2.64,z:6.2+Math.floor(i/6)*1.05,vx:0,lives:4,passed:0,eliminated:false,outAt:0,aiTarget:0})}}
function spawnWall(){wallCount++;const seq=activeMap.gaps;const gap=seq[(wallCount-1)%seq.length]*1.28,gapW=Math.max(1.0,3.0-wallCount*.045),speed=5.8+Math.min(12,wallCount*.27),g=new THREE.Group(),m=mat(activeMap.colors[wallCount%2]);const leftW=Math.max(.1,(gap+8)-gapW/2),rightW=Math.max(.1,8-(gap+gapW/2));if(leftW>.15){const a=new THREE.Mesh(new THREE.BoxGeometry(leftW,3.2,.55),m);a.position.set(-8+leftW/2,1.6,0);g.add(a)}if(rightW>.15){const b=new THREE.Mesh(new THREE.BoxGeometry(rightW,3.2,.55),m);b.position.set(gap+gapW/2+rightW/2,1.6,0);g.add(b)}g.position.z=-15;world.add(g);walls.push({g,gap,gapW,speed,hit:false})}
function rank(){return players.slice().sort((a,b)=>{if(a.eliminated!==b.eliminated)return a.eliminated?1:-1;if(a.eliminated&&b.eliminated&&a.outAt!==b.outAt)return b.outAt-a.outAt;if(a.lives!==b.lives)return b.lives-a.lives;if(a.passed!==b.passed)return b.passed-a.passed;return Math.abs(a.x)-Math.abs(b.x)})}
function hit(p){if(p.eliminated)return;p.lives--;p.vx+=(p.x<0?-1:1)*2.2;if(p.id===0)toast(p.lives?`HIT · ${p.lives} LIVES`:'OUT');if(p.lives<=0){p.eliminated=true;p.outAt=++outSeq;if(p.id===0)toast('OUT · WATCHING')}}
function stepPlayer(p,dt){if(p.eliminated){p.g.visible=false;return}p.g.visible=true;let dir=0;if(p.id===0)dir=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0);else{const next=walls.find(w=>!w.hit&&w.g.position.z<10);if(next){const target=next.gap+(p.id%3-1)*.25;dir=Math.sign(target-p.x)}dir*=.8+(p.id%3)*.07}const target=dir*7.1,blend=1-Math.exp(-10*dt);p.vx+=(target-p.vx)*blend;p.x+=p.vx*dt;p.x=Math.max(-7.45,Math.min(7.45,p.x));p.g.position.set(p.x,.05,p.z);p.g.rotation.y=Math.PI;const ph=elapsed*10+p.id;p.g.userData.a.rotation.x=Math.sin(ph)*Math.min(.55,Math.abs(p.vx)/8);p.g.userData.bb.rotation.x=-p.g.userData.a.rotation.x}
function updateWalls(dt){wallTimer-=dt;if(wallTimer<=0){spawnWall();wallTimer=Math.max(.62,2.35-wallCount*.043)}for(const w of walls){w.g.position.z+=w.speed*dt;if(!w.hit&&w.g.position.z>=6.2){w.hit=true;for(const p of players){if(p.eliminated)continue;const safe=Math.abs(p.x-w.gap)<w.gapW/2-.18;if(safe)p.passed++;else hit(p)}}}for(let i=walls.length-1;i>=0;i--){if(walls[i].g.position.z>18){world.remove(walls[i].g);walls.splice(i,1)}}}
function board(){const r=rank(),place=r.findIndex(p=>p.id===0)+1;$('metric1').textContent=`#${place}`;$('metric2').textContent=`${players[0].lives} ♥`;$('leaderboard').innerHTML=r.map((p,i)=>`<div class="lb-row ${p.id===0?'you':''}"><b>${i+1}</b><span>${p.name}</span><span>${p.eliminated?'OUT':p.lives+'♥ · '+p.passed}</span></div>`).join('');$('walletValue').textContent=money(wallet)}
function settle(place,reason){if(finished)return;finished=true;state='result';const prize=place<=3?PAYOUTS[place-1]:0;wallet+=prize;account.totalPrizes=(account.totalPrizes||0)+prize;if(place===1)account.wins=(account.wins||0)+1;account.totalMatches=(account.totalMatches||0)+1;account.matches=account.matches||[];account.matches.unshift({game:'wall-dodge',gameName:'Wall Dodge',place,prize,net:prize-ENTRY,lobby:ENTRY,mapName:activeMap?.name||'',detail:`${activeMap?.name||'Wall course'} · ${players[0].passed} walls · ${players[0].lives} lives`});account.matches=account.matches.slice(0,50);save();$('resultPlace').textContent=`#${place}`;$('resultTitle').textContent=place<=3?'PODIUM FINISH':'FINISHED';$('resultReason').textContent=reason;$('resultEntry').textContent=`-${money(ENTRY)}`;$('resultPrize').textContent=`+${money(prize)}`;$('resultMetric').textContent=`${players[0].passed} walls`;$('resultNet').textContent=signed(prize-ENTRY);$('resultWallet').textContent=money(wallet);$('playAgainBtn').textContent=wallet>=ENTRY?`PLAY AGAIN · ${money(ENTRY)}`:'BACK TO ARCADE';$('leaveBtn').classList.add('hidden');setTimeout(()=>{$('overlay').classList.add('show');$('menuPanel').classList.add('hidden');$('resultPanel').classList.remove('hidden')},220)}
function begin(){if(wallet<ENTRY)return;wallet-=ENTRY;save();economy();reset();count=3;elapsed=0;finished=false;state='countdown';$('overlay').classList.remove('show');$('menuPanel').classList.add('hidden');$('resultPanel').classList.add('hidden');$('countdown').classList.remove('hidden');$('leaveBtn').classList.remove('hidden')}
function forfeit(){if(!['play','countdown'].includes(state))return;account.totalMatches=(account.totalMatches||0)+1;account.matches.unshift({game:'wall-dodge',gameName:'Wall Dodge',mapName:activeMap?.name||'',forfeit:true,net:-ENTRY,lobby:ENTRY,detail:`${activeMap?.name||'Wall course'} · Match left`});save();location.href='../../index.html'}
function step(dt){if(state==='countdown'){count-=dt;$('countdownNumber').textContent=String(Math.max(1,Math.ceil(count)));if(count<=0){state='play';$('countdown').classList.add('hidden');toast(`DODGE THE WALLS · ${activeMap.name}`)}}if(state==='play'){elapsed+=dt;for(const p of players)stepPlayer(p,dt);updateWalls(dt);const live=players.filter(p=>!p.eliminated);if(live.length<=1&&wallCount>2&&!finished){const r=rank();settle(r.findIndex(p=>p.id===0)+1,'Last player standing.')}}}
function frame(n){const dt=Math.min(.05,(n-last)/1000||0);last=n;acc+=dt;while(acc>=FIXED){step(FIXED);acc-=FIXED}if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}camera.position.set(0,11.5,18.5);camera.lookAt(0,1,1);board();renderer.render(scene,camera);requestAnimationFrame(frame)}
$('actionTouch').classList.add('hidden');reset();
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space')e.preventDefault()});addEventListener('keyup',e=>keys.delete(e.code));document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();keys.add(k)};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>keys.delete(k)});$('startBtn').onclick=begin;$('playAgainBtn').onclick=()=>wallet>=ENTRY?begin():location.href='../../index.html';$('leaveBtn').onclick=forfeit;economy();board();requestAnimationFrame(frame);
})();