(()=>{'use strict';
const $=id=>document.getElementById(id);if(!window.THREE){$('startBtn').disabled=true;return}const THREE=window.THREE,qs=new URLSearchParams(location.search),raw=Number(qs.get('entry')),ENTRY=[1,5,20].includes(raw)?raw:1,STORAGE='skillArcadeDemoAccountV1',PLAYERS=8,ROUND=60,FEE=.05,PAYOUTS=[4.5,2.1,1].map(v=>v*ENTRY),POOL=PLAYERS*ENTRY*(1-FEE),FIXED=1/120;
const keys=new Set(),players=[],coins=[];let account=load(),wallet=account.wallet,state='menu',time=ROUND,count=3,last=performance.now(),acc=0,elapsed=0,dashBuffer=0,spawnIndex=0,spawnClock=0,toastT=0,finished=false;
function load(){const f={wallet:25,totalPrizes:0,wins:0,totalMatches:0,matches:[]};try{const d=JSON.parse(localStorage.getItem(STORAGE)||'null');return d?{...f,...d,matches:Array.isArray(d.matches)?d.matches:[]}:f}catch{return f}}function save(){account.wallet=Math.max(0,wallet);localStorage.setItem(STORAGE,JSON.stringify(account))}function money(v){return `$${Math.max(0,+v||0).toFixed(2)}`}function signed(v){return `${v>=0?'+':'-'}$${Math.abs(v).toFixed(2)}`}function toast(s){$('toast').textContent=s;$('toast').classList.add('show');toastT=.75}
function economy(){$('entryValue').textContent=money(ENTRY);$('poolValue').textContent=money(POOL);$('p1').textContent=money(PAYOUTS[0]);$('p2').textContent=money(PAYOUTS[1]);$('p3').textContent=money(PAYOUTS[2]);$('walletValue').textContent=$('lobbyWallet').textContent=money(wallet);$('startBtn').textContent=wallet>=ENTRY?`ENTER MATCH · ${money(ENTRY)}`:'INSUFFICIENT DEMO BALANCE';$('startBtn').disabled=wallet<ENTRY}
const renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.shadowMap.enabled=true;const scene=new THREE.Scene();scene.background=new THREE.Color(0x18222d);scene.fog=new THREE.Fog(0x18222d,25,55);const camera=new THREE.PerspectiveCamera(57,1,.05,90);camera.position.set(0,14,14);camera.lookAt(0,0,0);scene.add(camera);scene.add(new THREE.HemisphereLight(0xe8f5ff,0x2b3440,1.7));const sun=new THREE.DirectionalLight(0xffffff,1.8);sun.position.set(-10,18,10);sun.castShadow=true;scene.add(sun);const world=new THREE.Group(),actors=new THREE.Group(),coinGroup=new THREE.Group();scene.add(world,actors,coinGroup);const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.68});const floor=new THREE.Mesh(new THREE.BoxGeometry(18,.5,18),mat(0x315b64));floor.position.y=-.25;floor.receiveShadow=true;world.add(floor);for(const [w,d,x,z] of [[18,.25,0,-9],[18,.25,0,9],[.25,18,-9,0],[.25,18,9,0]]){const rail=new THREE.Mesh(new THREE.BoxGeometry(w,.65,d),mat(0x1f353a));rail.position.set(x,.25,z);world.add(rail)}
const colors=[0xffd84e,0xff6e9d,0x60d9b7,0x61c5ff,0xb18cff,0xff8a55,0x82e26f,0x4fc6d9],names=['You','Nova','Mika','Rook','Volt','Pip','Zed','Kira'];function bean(i){const g=new THREE.Group(),b=mat(colors[i]),d=mat(0x25313b);const body=new THREE.Mesh(new THREE.SphereGeometry(.42,14,10),b);body.scale.set(.9,1.1,.78);body.position.y=.72;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.29,14,10),b);head.position.y=1.18;g.add(head);const legs=new THREE.CylinderGeometry(.08,.1,.38,8),a=new THREE.Mesh(legs,d),bb=a.clone();a.position.set(-.15,.22,0);bb.position.set(.15,.22,0);g.add(a,bb);if(i===0)window.addYouMarker3D?.(THREE,g,{radius:.68,labelY:1.88});g.userData={a,bb};return g}
function reset(){actors.clear();coinGroup.clear();coins.length=0;players.length=0;const pts=[[-6,-6],[-2,-6],[2,-6],[6,-6],[-6,6],[-2,6],[2,6],[6,6]];for(let i=0;i<PLAYERS;i++){const g=bean(i);actors.add(g);players.push({id:i,name:names[i],g,pos:new THREE.Vector3(pts[i][0],.2,pts[i][1]),vel:new THREE.Vector3(),bot:i>0,score:0,dashCd:0,dashT:0,facing:new THREE.Vector2(0,-1),lastScore:999})}spawnIndex=0;spawnClock=0;for(let i=0;i<24;i++)spawnCoin()}
function coord(i){const k=(i*37+11)%121,r=Math.floor(k/11),c=k%11;return[(c-5)*1.45,(r-5)*1.45]}
function spawnCoin(){const [x,z]=coord(spawnIndex),gold=spawnIndex%9===8,val=gold?3:1,m=new THREE.MeshStandardMaterial({color:gold?0xffc928:0x89f2c4,emissive:gold?0x8a5a00:0x174d39,emissiveIntensity:.8,metalness:.25,roughness:.3}),mesh=new THREE.Mesh(new THREE.TorusGeometry(.28,.09,10,20),m);mesh.position.set(x,.48,z);mesh.rotation.x=Math.PI/2;coinGroup.add(mesh);coins.push({mesh,x,z,val,alive:true});spawnIndex++}
reset();function nearestCoin(p){let best=null,bd=1e9;for(const c of coins){if(!c.alive)continue;const d=(c.x-p.pos.x)**2+(c.z-p.pos.z)**2-(c.val-1)*1.8;if(d<bd){bd=d;best=c}}return best}
function input(p){if(!p.bot)return{x:(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),z:(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0),dash:dashBuffer>0};const c=nearestCoin(p);if(!c)return{x:0,z:0,dash:false};let x=c.x-p.pos.x,z=c.z-p.pos.z,l=Math.hypot(x,z)||1;x/=l;z/=l;return{x,z,dash:p.dashCd<=0&&l<4&&((Math.floor(elapsed*2)+p.id)%5===0)}}
function updatePlayer(p,dt){p.dashCd=Math.max(0,p.dashCd-dt);p.dashT=Math.max(0,p.dashT-dt);const a=input(p),l=Math.hypot(a.x,a.z),blend=1-Math.exp(-12*dt);if(l>.05){const nx=a.x/l,nz=a.z/l;p.facing.set(nx,nz);const sp=5;p.vel.x+=(nx*sp-p.vel.x)*blend;p.vel.z+=(nz*sp-p.vel.z)*blend}else{p.vel.x*=Math.exp(-9*dt);p.vel.z*=Math.exp(-9*dt)}if(a.dash&&p.dashCd<=0){p.dashCd=1.15;p.dashT=.2;p.vel.x=p.facing.x*10.5;p.vel.z=p.facing.y*10.5;if(!p.bot)dashBuffer=0}p.pos.x+=p.vel.x*dt;p.pos.z+=p.vel.z*dt;p.pos.x=Math.max(-8.25,Math.min(8.25,p.pos.x));p.pos.z=Math.max(-8.25,Math.min(8.25,p.pos.z));p.g.position.copy(p.pos);const ph=elapsed*10+p.id,sp=Math.hypot(p.vel.x,p.vel.z);p.g.userData.a.rotation.x=Math.sin(ph)*(sp>.3?.5:0);p.g.userData.bb.rotation.x=-p.g.userData.a.rotation.x;p.g.rotation.y=Math.atan2(p.facing.x,p.facing.y)}
function collisions(){for(const p of players)for(const c of coins){if(!c.alive)continue;if(Math.hypot(p.pos.x-c.x,p.pos.z-c.z)<.62){c.alive=false;c.mesh.visible=false;p.score+=c.val;p.lastScore=elapsed;if(p.id===0)toast(c.val===3?'+3 GOLD':'+1')}}for(let i=0;i<players.length;i++)for(let j=i+1;j<players.length;j++){const a=players[i],b=players[j],dx=b.pos.x-a.pos.x,dz=b.pos.z-a.pos.z,d=Math.hypot(dx,dz);if(d<.72&&d>.001){const nx=dx/d,nz=dz/d,push=(.72-d)*.18;a.pos.x-=nx*push;a.pos.z-=nz*push;b.pos.x+=nx*push;b.pos.z+=nz*push}}}
function rank(){return players.slice().sort((a,b)=>b.score-a.score||a.lastScore-b.lastScore||a.id-b.id)}function board(){const r=rank(),place=r.findIndex(p=>p.id===0)+1;$('metric1').textContent=String(players[0].score);$('metric2').textContent=`${Math.ceil(time)}s`;$('leaderboard').innerHTML=r.map((p,i)=>`<div class="lb-row ${p.id===0?'you':''}"><b>${i+1}</b><span>${p.name}</span><span>${p.score}</span></div>`).join('');$('walletValue').textContent=money(wallet)}
function end(){if(finished)return;finished=true;state='result';const r=rank(),place=r.findIndex(p=>p.id===0)+1,prize=place<=3?PAYOUTS[place-1]:0;wallet+=prize;account.totalPrizes=(account.totalPrizes||0)+prize;if(place===1)account.wins=(account.wins||0)+1;account.totalMatches=(account.totalMatches||0)+1;account.matches=account.matches||[];account.matches.unshift({game:'coin-rush',gameName:'Coin Rush',place,prize,net:prize-ENTRY,lobby:ENTRY,detail:`${players[0].score} coins`,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})});account.matches=account.matches.slice(0,50);save();$('resultPlace').textContent=`#${place}`;$('resultTitle').textContent=place<=3?'PODIUM FINISH':'ROUND OVER';$('resultReason').textContent=`You collected ${players[0].score} points.`;$('resultEntry').textContent=`-${money(ENTRY)}`;$('resultPrize').textContent=`+${money(prize)}`;$('resultMetric').textContent=String(players[0].score);$('resultNet').textContent=signed(prize-ENTRY);$('resultWallet').textContent=money(wallet);$('playAgainBtn').textContent=wallet>=ENTRY?`PLAY AGAIN · ${money(ENTRY)}`:'BACK TO ARCADE';$('leaveBtn').classList.add('hidden');setTimeout(()=>{$('overlay').classList.add('show');$('menuPanel').classList.add('hidden');$('resultPanel').classList.remove('hidden')},250)}
function begin(){if(wallet<ENTRY)return;wallet-=ENTRY;save();economy();reset();time=ROUND;count=3;elapsed=0;finished=false;state='countdown';$('overlay').classList.remove('show');$('menuPanel').classList.add('hidden');$('resultPanel').classList.add('hidden');$('countdown').classList.remove('hidden');$('leaveBtn').classList.remove('hidden');toast('COLLECT THE MOST COINS')}
function forfeit(){if(!['play','countdown'].includes(state))return;account.totalMatches=(account.totalMatches||0)+1;account.matches=account.matches||[];account.matches.unshift({game:'coin-rush',gameName:'Coin Rush',forfeit:true,net:-ENTRY,lobby:ENTRY,detail:'Match left'});save();location.href='../../index.html'}
function step(dt){dashBuffer=Math.max(0,dashBuffer-dt);if(state==='countdown'){count-=dt;$('countdownNumber').textContent=String(Math.max(1,Math.ceil(count)));if(count<=0){state='play';$('countdown').classList.add('hidden');toast('GO!')}}if(state==='play'){elapsed+=dt;time=Math.max(0,time-dt);for(const p of players)updatePlayer(p,dt);collisions();spawnClock+=dt;if(spawnClock>.7){spawnClock=0;const dead=coins.find(c=>!c.alive);if(dead){dead.alive=true;dead.mesh.visible=true;const [x,z]=coord(spawnIndex);dead.x=x;dead.z=z;dead.val=spawnIndex%9===8?3:1;dead.mesh.position.set(x,.48,z);dead.mesh.material.color.setHex(dead.val===3?0xffc928:0x89f2c4);spawnIndex++}else if(coins.length<32)spawnCoin()}for(const c of coins)if(c.alive)c.mesh.rotation.z+=dt*2.2;if(time<=0)end()}}
function frame(n){const dt=Math.min(.05,(n-last)/1000||0);last=n;acc+=dt;while(acc>=FIXED){step(FIXED);acc-=FIXED}if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}board();renderer.render(scene,camera);requestAnimationFrame(frame)}function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space'){e.preventDefault();dashBuffer=.15}});addEventListener('keyup',e=>keys.delete(e.code));document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();keys.add(k)};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>keys.delete(k)});$('actionTouch').onpointerdown=e=>{e.preventDefault();dashBuffer=.15};$('startBtn').onclick=begin;$('playAgainBtn').onclick=()=>wallet>=ENTRY?begin():location.href='../../index.html';$('leaveBtn').onclick=forfeit;economy();board();requestAnimationFrame(frame);
})();
