(()=>{'use strict';
const $=id=>document.getElementById(id);if(!window.THREE){$('startBtn').disabled=true;return}const THREE=window.THREE,qs=new URLSearchParams(location.search),raw=Number(qs.get('entry')),ENTRY=[1,5,20].includes(raw)?raw:1,STORAGE='skillArcadeDemoAccountV1',FEE=.05,FIXED=1/120;
const keys=new Set();let account=load(),wallet=account.wallet,state='menu',count=3,last=performance.now(),acc=0,elapsed=0,toastT=0,finished=false;
function load(){const f={wallet:25,totalPrizes:0,wins:0,totalMatches:0,matches:[]};try{const d=JSON.parse(localStorage.getItem(STORAGE)||'null');return d?{...f,...d,matches:Array.isArray(d.matches)?d.matches:[]}:f}catch{return f}}function save(){account.wallet=Math.max(0,wallet);localStorage.setItem(STORAGE,JSON.stringify(account))}function money(v){return `$${Math.max(0,+v||0).toFixed(2)}`}function signed(v){return `${v>=0?'+':'-'}$${Math.abs(v).toFixed(2)}`}function toast(s){$('toast').textContent=s;$('toast').classList.add('show');toastT=1.1}

const PLAYERS=12,ARENA_R=10.4,PAYOUTS=[6,3.4,2].map(v=>v*ENTRY),POOL=PLAYERS*ENTRY*(1-FEE),names=['You','Nova','Mika','Rook','Volt','Pip','Zed','Kira','Atlas','Echo','Juno','Blaze'],colors=[0xffd84e,0xff5f83,0x55d6b0,0x53c8ff,0x9f7cff,0xff8a4f,0x77dd67,0x42d1d6,0xffb347,0xe66cff,0x6f8cff,0xff6b57];let players=[],strikes=[],strikeTimer=1,dashLatch=false,seq=0,outSeq=0,activeMap=null;
const METEOR_MAPS=[
{id:'ember',name:'Ember Ring',sky:0x18213d,floor:0x354b6b,border:0x7aa8ff,seed:0},
{id:'violet',name:'Violet Orbit',sky:0x261b3f,floor:0x4b3e69,border:0xc08cff,seed:17},
{id:'frost',name:'Frost Circle',sky:0x16313b,floor:0x315a63,border:0x72e6ff,seed:31},
{id:'sunset',name:'Sunset Ring',sky:0x3a1f2a,floor:0x68424a,border:0xffa45f,seed:53}
];
function economy(){$('entryValue').textContent=money(ENTRY);$('poolValue').textContent=money(POOL);$('p1').textContent=money(PAYOUTS[0]);$('p2').textContent=money(PAYOUTS[1]);$('p3').textContent=money(PAYOUTS[2]);$('walletValue').textContent=$('lobbyWallet').textContent=money(wallet);$('startBtn').textContent=wallet>=ENTRY?`ENTER MATCH · ${money(ENTRY)}`:'INSUFFICIENT DEMO BALANCE';$('startBtn').disabled=wallet<ENTRY}
const renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));const scene=new THREE.Scene();scene.background=new THREE.Color(0x18213d);const camera=new THREE.PerspectiveCamera(56,1,.05,100);scene.add(new THREE.HemisphereLight(0xaecbff,0x201522,1.5));const sun=new THREE.DirectionalLight(0xffffff,1.2);sun.position.set(-7,15,8);scene.add(sun);const world=new THREE.Group(),actors=new THREE.Group(),fx=new THREE.Group();scene.add(world,actors,fx);const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.72});const floorMat=mat(0x354b6b),floor=new THREE.Mesh(new THREE.CylinderGeometry(10.9,10.9,.5,64),floorMat);floor.position.y=-.3;world.add(floor);const borderMat=new THREE.MeshStandardMaterial({color:0x7aa8ff,emissive:0x427fff,emissiveIntensity:.7}),border=new THREE.Mesh(new THREE.TorusGeometry(10.8,.12,8,64),borderMat);border.rotation.x=Math.PI/2;border.position.y=.02;world.add(border);
function bean(i){return window.SkillArcadeCharacters?.make(THREE,i,{colors,scale:.98,markerRadius:.72,labelY:2.08})||new THREE.Group()}
function reset(){if(!activeMap||state==='result')activeMap=window.SkillArcadeMaps?.pick('meteor-dodge',METEOR_MAPS)||METEOR_MAPS[0];scene.background.setHex(activeMap.sky);floorMat.color.setHex(activeMap.floor);borderMat.color.setHex(activeMap.border);borderMat.emissive.setHex(activeMap.border);actors.clear();while(fx.children.length)fx.remove(fx.children[0]);players=[];strikes=[];seq=0;outSeq=0;strikeTimer=1.05;for(let i=0;i<PLAYERS;i++){const a=i/PLAYERS*Math.PI*2,g=bean(i);actors.add(g);players.push({id:i,name:names[i],g,pos:new THREE.Vector3(Math.cos(a)*7.1,.05,Math.sin(a)*7.1),vel:new THREE.Vector3(),lives:4,dash:0,eliminated:false,outAt:0,bot:i>0})}}
function pattern(i,j){const q=i+(activeMap?.seed||0),a=(q*2.399+j*1.77),r=2.0+((q*37+j*19)%58)/10;return{x:Math.cos(a)*Math.min(9.45,r+1.2),z:Math.sin(a)*Math.min(9.45,r+1.2)}}function spawnStrike(){const count=Math.min(5,1+Math.floor(seq/11)),warn=Math.max(.68,1.28-seq*.008),rad=Math.min(1.32,.92+seq*.008);for(let j=0;j<count;j++){const p=pattern(seq,j),ring=new THREE.Mesh(new THREE.RingGeometry(rad,rad+.14,32),new THREE.MeshBasicMaterial({color:0xff4d5e,transparent:true,opacity:.78,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.set(p.x,.02,p.z);fx.add(ring);strikes.push({x:p.x,z:p.z,t:warn,warn,rad,ring,fired:false})}seq++}
function input(p){if(p.bot){let tx=0,tz=0,best=999;for(const s of strikes)if(!s.fired){const d=Math.hypot(p.pos.x-s.x,p.pos.z-s.z);if(d<best){best=d;tx=p.pos.x-s.x;tz=p.pos.z-s.z}}if(best<3.2){const l=Math.hypot(tx,tz)||1;return{x:tx/l,z:tz/l,dash:p.dash<=0&&best<2.0}}return{x:Math.sin(elapsed*.7+p.id),z:Math.cos(elapsed*.53+p.id),dash:false}}return{x:(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),z:(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0),dash:keys.has('Space')}}
function updatePlayer(p,dt){if(p.eliminated){p.g.visible=false;return}p.dash=Math.max(0,p.dash-dt);const a=input(p),l=Math.hypot(a.x,a.z),blend=1-Math.exp(-10*dt);if(a.dash&&p.dash<=0&&l>.05){p.vel.x+=a.x/l*6;p.vel.z+=a.z/l*6;p.dash=1.35}else if(l>.05){p.vel.x+=(a.x/l*5-p.vel.x)*blend;p.vel.z+=(a.z/l*5-p.vel.z)*blend}else{p.vel.x*=Math.exp(-7*dt);p.vel.z*=Math.exp(-7*dt)}p.pos.addScaledVector(p.vel,dt);const edge=Math.hypot(p.pos.x,p.pos.z);if(edge>ARENA_R){const nx=p.pos.x/edge,nz=p.pos.z/edge;p.pos.x=nx*ARENA_R;p.pos.z=nz*ARENA_R;const outward=p.vel.x*nx+p.vel.z*nz;if(outward>0){p.vel.x-=nx*outward*1.2;p.vel.z-=nz*outward*1.2}}p.g.position.copy(p.pos);p.g.rotation.y=Math.atan2(p.vel.x,p.vel.z)||0}
function hit(p){if(p.eliminated)return;p.lives--;p.vel.set(0,0,0);p.pos.set((p.id%4-1.5)*1.1,.05,Math.floor(p.id/4)*1.1-.55);if(p.id===0)toast(p.lives?`HIT · ${p.lives} LIVES`:'OUT');if(p.lives<=0){p.eliminated=true;p.outAt=++outSeq;if(p.id===0)toast('OUT · WATCHING')}}
function updateStrikes(dt){strikeTimer-=dt;if(strikeTimer<=0){spawnStrike();strikeTimer=Math.max(.68,1.72-seq*.014)}for(const s of strikes){s.t-=dt;s.ring.material.opacity=Math.max(.15,s.t/Math.max(.01,s.warn));s.ring.scale.setScalar(1+(1-s.t/Math.max(.01,s.warn))*.12);if(!s.fired&&s.t<=0){s.fired=true;s.ring.material.color.set(0xffffff);s.ring.material.opacity=1;const beam=new THREE.Mesh(new THREE.CylinderGeometry(s.rad*.82,s.rad,10,20),new THREE.MeshBasicMaterial({color:0xffb03b,transparent:true,opacity:.72}));beam.position.set(s.x,5,s.z);fx.add(beam);s.beam=beam;for(const p of players)if(!p.eliminated&&Math.hypot(p.pos.x-s.x,p.pos.z-s.z)<s.rad+.18)hit(p)}if(s.fired&&s.beam){s.beam.material.opacity-=dt*2.8;s.beam.scale.x*=.995;s.beam.scale.z*=.995}}for(let i=strikes.length-1;i>=0;i--){const s=strikes[i];if(s.fired&&(!s.beam||s.beam.material.opacity<=0)){fx.remove(s.ring);if(s.beam)fx.remove(s.beam);strikes.splice(i,1)}}}
function rank(){return players.slice().sort((a,b)=>{if(a.eliminated!==b.eliminated)return a.eliminated?1:-1;if(a.eliminated&&b.eliminated&&a.outAt!==b.outAt)return b.outAt-a.outAt;if(a.lives!==b.lives)return b.lives-a.lives;return Math.hypot(b.pos.x,b.pos.z)-Math.hypot(a.pos.x,a.pos.z)})}
function board(){const r=rank(),place=r.findIndex(p=>p.id===0)+1;$('metric1').textContent=`#${place}`;$('metric2').textContent=`${players[0].lives} ♥`;$('leaderboard').innerHTML=r.map((p,i)=>`<div class="lb-row ${p.id===0?'you':''}"><b>${i+1}</b><span>${p.name}</span><span>${p.eliminated?'OUT':p.lives+'♥'}</span></div>`).join('');$('walletValue').textContent=money(wallet)}
function settle(place,reason){if(finished)return;finished=true;state='result';const prize=place<=3?PAYOUTS[place-1]:0;wallet+=prize;account.totalPrizes=(account.totalPrizes||0)+prize;if(place===1)account.wins=(account.wins||0)+1;account.totalMatches=(account.totalMatches||0)+1;account.matches=account.matches||[];account.matches.unshift({game:'meteor-dodge',gameName:'Meteor Dodge',place,prize,net:prize-ENTRY,lobby:ENTRY,mapName:activeMap?.name||'',detail:`${activeMap?.name||'Arena'} · ${players[0].lives} lives`});account.matches=account.matches.slice(0,50);save();$('resultPlace').textContent=`#${place}`;$('resultTitle').textContent=place<=3?'PODIUM FINISH':'FINISHED';$('resultReason').textContent=reason;$('resultEntry').textContent=`-${money(ENTRY)}`;$('resultPrize').textContent=`+${money(prize)}`;$('resultMetric').textContent=`${players[0].lives} lives`;$('resultNet').textContent=signed(prize-ENTRY);$('resultWallet').textContent=money(wallet);$('playAgainBtn').textContent=wallet>=ENTRY?`PLAY AGAIN · ${money(ENTRY)}`:'BACK TO ARCADE';$('leaveBtn').classList.add('hidden');setTimeout(()=>{$('overlay').classList.add('show');$('menuPanel').classList.add('hidden');$('resultPanel').classList.remove('hidden')},220)}
function begin(){if(wallet<ENTRY)return;wallet-=ENTRY;save();economy();reset();count=3;elapsed=0;finished=false;state='countdown';$('overlay').classList.remove('show');$('menuPanel').classList.add('hidden');$('resultPanel').classList.add('hidden');$('countdown').classList.remove('hidden');$('leaveBtn').classList.remove('hidden')}
function forfeit(){if(!['play','countdown'].includes(state))return;account.totalMatches=(account.totalMatches||0)+1;account.matches.unshift({game:'meteor-dodge',gameName:'Meteor Dodge',mapName:activeMap?.name||'',forfeit:true,net:-ENTRY,lobby:ENTRY,detail:`${activeMap?.name||'Arena'} · Match left`});save();location.href='../../index.html'}
function step(dt){if(state==='countdown'){count-=dt;$('countdownNumber').textContent=String(Math.max(1,Math.ceil(count)));if(count<=0){state='play';$('countdown').classList.add('hidden');toast(`DODGE THE STRIKES · ${activeMap.name}`)}}if(state==='play'){elapsed+=dt;for(const p of players)updatePlayer(p,dt);updateStrikes(dt);const live=players.filter(p=>!p.eliminated);if(live.length<=1&&!finished){const r=rank();settle(r.findIndex(p=>p.id===0)+1,'Last player standing.')}}}
function frame(n){const dt=Math.min(.05,(n-last)/1000||0);last=n;acc+=dt;while(acc>=FIXED){step(FIXED);acc-=FIXED}if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}camera.position.set(0,19.5,17.2);camera.lookAt(0,0,0);board();renderer.render(scene,camera);requestAnimationFrame(frame)}
$('actionTouch').textContent='DASH';$('actionTouch').onpointerdown=e=>{e.preventDefault();keys.add('Space')};$('actionTouch').onpointerup=$('actionTouch').onpointercancel=()=>keys.delete('Space');reset();
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space')e.preventDefault()});addEventListener('keyup',e=>keys.delete(e.code));document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();keys.add(k)};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>keys.delete(k)});$('startBtn').onclick=begin;$('playAgainBtn').onclick=()=>wallet>=ENTRY?begin():location.href='../../index.html';$('leaveBtn').onclick=forfeit;economy();board();requestAnimationFrame(frame);
})();