(()=>{'use strict';
const $=id=>document.getElementById(id);if(!window.THREE){$('startBtn').disabled=true;$('startBtn').textContent='3D ENGINE FAILED';return}const THREE=window.THREE;
const qs=new URLSearchParams(location.search),e=Number(qs.get('entry')),ENTRY=[1,5,20].includes(e)?e:1,STORAGE='skillArcadeDemoAccountV1',PLAYERS=12,FEE=.05,PAYOUTS=[6,3.4,2].map(v=>v*ENTRY),POOL=PLAYERS*ENTRY*(1-FEE),FIXED=1/120;
const keys=new Set(),players=[],dead=[],tiles=[];let account=load(),wallet=account.wallet,state='menu',count=3,last=performance.now(),acc=0,elapsed=0,toastT=0;
function load(){const f={wallet:25,totalPrizes:0,wins:0,totalMatches:0,matches:[]};try{const d=JSON.parse(localStorage.getItem(STORAGE)||'null');return d?{...f,...d,matches:Array.isArray(d.matches)?d.matches:[]}:f}catch{return f}}function save(){account.wallet=Math.max(0,wallet);localStorage.setItem(STORAGE,JSON.stringify(account))}function money(v){return `$${Math.max(0,+v||0).toFixed(2)}`}function signed(v){return `${v>=0?'+':'-'}$${Math.abs(v).toFixed(2)}`}function toast(s){$('toast').textContent=s;$('toast').classList.add('show');toastT=1}
function economy(){$('entryValue').textContent=money(ENTRY);$('poolValue').textContent=money(POOL);$('p1').textContent=money(PAYOUTS[0]);$('p2').textContent=money(PAYOUTS[1]);$('p3').textContent=money(PAYOUTS[2]);$('walletValue').textContent=$('lobbyWallet').textContent=money(wallet);$('startBtn').textContent=wallet>=ENTRY?`ENTER MATCH · ${money(ENTRY)}`:'INSUFFICIENT DEMO BALANCE';$('startBtn').disabled=wallet<ENTRY}
const renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.shadowMap.enabled=true;const scene=new THREE.Scene();scene.background=new THREE.Color(0x10202b);scene.fog=new THREE.Fog(0x10202b,24,60);const camera=new THREE.PerspectiveCamera(55,1,.05,100);camera.position.set(0,23,15.5);camera.lookAt(0,0,0);scene.add(camera);scene.add(new THREE.HemisphereLight(0xc9e7ff,0x2d2a33,1.7));const sun=new THREE.DirectionalLight(0xffffff,1.8);sun.position.set(-10,18,8);sun.castShadow=true;scene.add(sun);const world=new THREE.Group(),actors=new THREE.Group();scene.add(world,actors);const mat=(c)=>new THREE.MeshStandardMaterial({color:c,roughness:.68});const lavaM=new THREE.MeshStandardMaterial({color:0xff4b16,emissive:0xff2100,emissiveIntensity:1.5});const lava=new THREE.Mesh(new THREE.BoxGeometry(29,.5,29),lavaM);lava.position.y=-4.3;world.add(lava);
const N=19,S=1.05,G=.065,SPAN=N*S;let activeMap=null;
const TILE_MAPS=[
{id:'classic',name:'Classic Grid',a:0x4b78a0,b:0x5889b2,life:(r,c)=>1},
{id:'checker',name:'Checker Pace',a:0x5b5fa8,b:0x7277c7,life:(r,c)=>(r+c)%2?0.92:1.12},
{id:'rings',name:'Ring Rush',a:0x3d8b78,b:0x55a88f,life:(r,c)=>0.9+Math.max(Math.abs(r-9),Math.abs(c-9))*.025},
{id:'lanes',name:'Lane Shift',a:0x9a5c7a,b:0xb66c90,life:(r,c)=>c%3===0?0.9:1.08}
];const colors=[0xffd84e,0xff5f83,0x55d6b0,0x53c8ff,0x9f7cff,0xff8a4f,0x77dd67,0x42d1d6,0xffb347,0xe66cff,0x6f8cff,0xff6b57],names=['You','Nova','Mika','Rook','Volt','Pip','Zed','Kira','Atlas','Echo','Juno','Blaze'];
function createTiles(){tiles.length=0;for(let r=0;r<N;r++)for(let c=0;c<N;c++){const m=mat((r+c)%2?0x4b78a0:0x5889b2),mesh=new THREE.Mesh(new THREE.BoxGeometry(S-G,.36,S-G),m);mesh.position.set((c-(N-1)/2)*S,0,(r-(N-1)/2)*S);mesh.receiveShadow=true;world.add(mesh);tiles.push({r,c,mesh,state:0,t:0})}}
createTiles();function bean(i){return window.SkillArcadeCharacters?.make(THREE,i,{colors,scale:.98,markerRadius:.72,labelY:2.08})||new THREE.Group()}
function tileAt(x,z){const c=Math.round(x/S+(N-1)/2),r=Math.round(z/S+(N-1)/2);if(r<0||r>=N||c<0||c>=N)return null;return tiles[r*N+c]}
function reset(){if(!activeMap||state==='result')activeMap=window.SkillArcadeMaps?.pick('falling-tiles',TILE_MAPS)||TILE_MAPS[0];actors.clear();dead.length=0;for(const t of tiles){t.state=0;t.t=0;t.mesh.visible=true;t.mesh.position.y=0;t.mesh.scale.set(1,1,1);t.mesh.material.transparent=false;t.mesh.material.opacity=1;t.mesh.material.color.setHex((t.r+t.c)%2?activeMap.a:activeMap.b)}players.length=0;const spawnR=SPAN*.36,pts=Array.from({length:PLAYERS},(_,i)=>{const a=i/PLAYERS*Math.PI*2-.2;return[Math.cos(a)*spawnR,Math.sin(a)*spawnR]});for(let i=0;i<PLAYERS;i++){const g=bean(i);actors.add(g);players.push({id:i,name:names[i],g,pos:new THREE.Vector3(pts[i][0],.2,pts[i][1]),vel:new THREE.Vector3(),alive:true,bot:i>0,turn:i*.8,tiles:0})}}
reset();function alive(){return players.filter(p=>p.alive)}
function input(p){if(!p.bot){const sx=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),sy=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),f=new THREE.Vector3();camera.getWorldDirection(f);f.y=0;f.normalize();const r=new THREE.Vector3().crossVectors(f,new THREE.Vector3(0,1,0)).normalize();return{x:r.x*sx+f.x*sy,z:r.z*sx+f.z*sy}};p.turn-=FIXED;let dx=Math.sin(elapsed*.7+p.id*1.4),dz=Math.cos(elapsed*.63+p.id*.9);const ahead=tileAt(p.pos.x+dx*1.2,p.pos.z+dz*1.2);if(!ahead||ahead.state===2||ahead.t>.45||p.turn<=0){p.turn=.45+.12*(p.id%3);const ang=elapsed*.9+p.id*1.7;dx=Math.cos(ang);dz=Math.sin(ang)}return{x:dx,z:dz}}
function updateTiles(dt){const baseFall=Math.max(.72,1.48-elapsed*.0046);for(const t of tiles){const fallAt=baseFall*(activeMap?.life?.(t.r,t.c)||1);if(t.state===1){t.t+=dt;if(t.t>fallAt*.55)t.mesh.material.color.setHex(0xffa84c);if(t.t>fallAt){t.state=2;t.t=0}}if(t.state===2){t.mesh.position.y-=7.2*dt;if(t.mesh.position.y<-4){t.mesh.position.y=-4;t.mesh.visible=false}}}}
function kill(p){if(!p.alive)return;p.alive=false;dead.push(p.id);p.g.visible=false;if(p.id===0)toast('OUT · WATCHING');if(alive().length<=1&&!finished)end(finalRank().findIndex(x=>x.id===0)+1,'Last player standing.')}
function updatePlayer(p,dt){if(!p.alive)return;const a=input(p),l=Math.hypot(a.x,a.z),blend=1-Math.exp(-18*dt);if(l>.05){const nx=a.x/l,nz=a.z/l;p.vel.x+=(nx*3.9-p.vel.x)*blend;p.vel.z+=(nz*3.9-p.vel.z)*blend}else{p.vel.x*=Math.exp(-15*dt);p.vel.z*=Math.exp(-15*dt)}const center=tileAt(p.pos.x,p.pos.z),offs=[[-.24,-.24],[.24,-.24],[-.24,.24],[.24,.24]],supported=offs.some(([ox,oz])=>{const t=tileAt(p.pos.x+ox,p.pos.z+oz);return t&&t.state!==2&&t.mesh.visible});if(p.pos.y<=.24&&supported){p.pos.y=.2;p.vel.y=0;if(center&&center.state===0){center.state=1;center.t=0;p.tiles++}}else p.vel.y-=18*dt;p.pos.addScaledVector(p.vel,dt);if(Math.abs(p.pos.x)>SPAN/2+.4||Math.abs(p.pos.z)>SPAN/2+.4)p.vel.y-=15*dt;if(p.pos.y<-3.5)kill(p);p.g.position.copy(p.pos);const sp=Math.hypot(p.vel.x,p.vel.z),ph=elapsed*10+p.id;p.g.userData.a.rotation.x=Math.sin(ph)*(sp>.3?.5:0);p.g.userData.bb.rotation.x=-p.g.userData.a.rotation.x}
function finalRank(){return alive().slice().sort((a,b)=>b.tiles-a.tiles).concat(dead.slice().reverse().map(id=>players[id]))}function board(){const r=finalRank();$('leaderboard').innerHTML=r.map((p,i)=>`<div class="lb-row ${p.id===0?'you':''}"><b>${i+1}</b><span>${p.name}</span><span>${p.alive?'IN':'OUT'}</span></div>`).join('');$('metric1').textContent=`${alive().length} / ${PLAYERS}`;$('metric2').textContent=String(tiles.filter(t=>t.state!==2).length);$('walletValue').textContent=money(wallet)}
let finished=false;function end(place,reason){if(finished||state==='menu')return;finished=true;state='result';const prize=place<=3?PAYOUTS[place-1]:0;wallet+=prize;account.totalPrizes=(account.totalPrizes||0)+prize;if(place===1)account.wins=(account.wins||0)+1;account.totalMatches=(account.totalMatches||0)+1;account.matches=account.matches||[];account.matches.unshift({game:'falling-tiles',gameName:'Falling Tiles',place,prize,net:prize-ENTRY,lobby:ENTRY,mapName:activeMap?.name||'',detail:`${activeMap?.name||'Grid'} · ${players[0].tiles} tiles crossed`,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})});account.matches=account.matches.slice(0,50);save();$('resultPlace').textContent=`#${place}`;$('resultTitle').textContent=place<=3?'PODIUM FINISH':'ELIMINATED';$('resultReason').textContent=reason;$('resultEntry').textContent=`-${money(ENTRY)}`;$('resultPrize').textContent=`+${money(prize)}`;$('resultMetric').textContent=String(players[0].tiles);$('resultNet').textContent=signed(prize-ENTRY);$('resultWallet').textContent=money(wallet);$('playAgainBtn').textContent=wallet>=ENTRY?`PLAY AGAIN · ${money(ENTRY)}`:'BACK TO ARCADE';$('leaveBtn').classList.add('hidden');setTimeout(()=>{$('overlay').classList.add('show');$('menuPanel').classList.add('hidden');$('resultPanel').classList.remove('hidden')},250)}
function begin(){if(wallet<ENTRY)return;wallet-=ENTRY;save();economy();reset();count=3;elapsed=0;finished=false;state='countdown';$('overlay').classList.remove('show');$('menuPanel').classList.add('hidden');$('resultPanel').classList.add('hidden');$('countdown').classList.remove('hidden');$('leaveBtn').classList.remove('hidden');toast(`KEEP MOVING · ${activeMap.name}`)}
function forfeit(){if(!['play','countdown'].includes(state))return;account.totalMatches=(account.totalMatches||0)+1;account.matches=account.matches||[];account.matches.unshift({game:'falling-tiles',gameName:'Falling Tiles',mapName:activeMap?.name||'',forfeit:true,net:-ENTRY,lobby:ENTRY,detail:`${activeMap?.name||'Grid'} · Match left`});save();location.href='../../index.html'}
function step(dt){if(state==='countdown'){count-=dt;$('countdownNumber').textContent=String(Math.max(1,Math.ceil(count)));if(count<=0){state='play';$('countdown').classList.add('hidden');toast('GO!')}}if(state==='play'){elapsed+=dt;updateTiles(dt);for(const p of players)updatePlayer(p,dt);if(alive().length<=1&&!finished)end(finalRank().findIndex(x=>x.id===0)+1,'Last player standing.')} }
function frame(n){const dt=Math.min(.05,(n-last)/1000||0);last=n;acc+=dt;while(acc>=FIXED){step(FIXED);acc-=FIXED}if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}board();renderer.render(scene,camera);requestAnimationFrame(frame)}function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();addEventListener('keydown',e=>keys.add(e.code));addEventListener('keyup',e=>keys.delete(e.code));document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();keys.add(k)};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>keys.delete(k)});$('actionTouch').classList.add('hidden');$('startBtn').onclick=begin;$('playAgainBtn').onclick=()=>wallet>=ENTRY?begin():location.href='../../index.html';$('leaveBtn').onclick=forfeit;economy();board();requestAnimationFrame(frame);
})();
