(()=>{'use strict';
const $=id=>document.getElementById(id);if(!window.THREE){$('startBtn').disabled=true;return}const THREE=window.THREE,qs=new URLSearchParams(location.search),raw=Number(qs.get('entry')),ENTRY=[1,5,20].includes(raw)?raw:1,STORAGE='skillArcadeDemoAccountV1',FEE=.05,FIXED=1/120;
const keys=new Set();let account=load(),wallet=account.wallet,state='menu',count=3,last=performance.now(),acc=0,elapsed=0,toastT=0,finished=false;
function load(){const f={wallet:25,totalPrizes:0,wins:0,totalMatches:0,matches:[]};try{const d=JSON.parse(localStorage.getItem(STORAGE)||'null');return d?{...f,...d,matches:Array.isArray(d.matches)?d.matches:[]}:f}catch{return f}}function save(){account.wallet=Math.max(0,wallet);localStorage.setItem(STORAGE,JSON.stringify(account))}function money(v){return `$${Math.max(0,+v||0).toFixed(2)}`}function signed(v){return `${v>=0?'+':'-'}$${Math.abs(v).toFixed(2)}`}function toast(s){$('toast').textContent=s;$('toast').classList.add('show');toastT=1.1}

const PLAYERS=12,ROUND=150,PAYOUTS=[6,3.4,2].map(v=>v*ENTRY),POOL=PLAYERS*ENTRY*(1-FEE),names=['You','Nova','Mika','Rook','Volt','Pip','Zed','Kira','Atlas','Echo','Juno','Blaze'],colors=[0xffd84e,0xff5f83,0x55d6b0,0x53c8ff,0x9f7cff,0xff8a4f,0x77dd67,0x42d1d6,0xffb347,0xe66cff,0x6f8cff,0xff6b57];let players=[],time=ROUND,grid=[],W=27,H=27,path=[],finishers=[],mapId=0,mapName='';
const MAZE_MAPS=[{id:'garden',name:'Garden Grid',seed:1337},{id:'switchback',name:'Switchback',seed:7331},{id:'metro',name:'Metro Maze',seed:2026},{id:'citadel',name:'Citadel',seed:4519},{id:'harbor',name:'Harbor Halls',seed:8841},{id:'orchard',name:'Orchard Run',seed:6173},{id:'cobalt',name:'Cobalt Corridors',seed:9427},{id:'sunset',name:'Sunset Maze',seed:3187},{id:'zigzag',name:'Zigzag Vault',seed:7711},{id:'spiral',name:'Spiral Yard',seed:5293},{id:'tunnel',name:'Tunnel Grid',seed:6607},{id:'summit',name:'Summit Maze',seed:1051}];
function economy(){$('entryValue').textContent=money(ENTRY);$('poolValue').textContent=money(POOL);$('p1').textContent=money(PAYOUTS[0]);$('p2').textContent=money(PAYOUTS[1]);$('p3').textContent=money(PAYOUTS[2]);$('walletValue').textContent=$('lobbyWallet').textContent=money(wallet);$('startBtn').textContent=wallet>=ENTRY?`ENTER MATCH · ${money(ENTRY)}`:'INSUFFICIENT DEMO BALANCE';$('startBtn').disabled=wallet<ENTRY}
const renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));const scene=new THREE.Scene();scene.background=new THREE.Color(0xb8e0ff);const camera=new THREE.PerspectiveCamera(55,1,.05,100);scene.add(new THREE.HemisphereLight(0xffffff,0x58695b,1.7));const sun=new THREE.DirectionalLight(0xffffff,1.4);sun.position.set(-10,18,8);scene.add(sun);const world=new THREE.Group(),actors=new THREE.Group();scene.add(world,actors);const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.75});
function rng(seed){let s=seed>>>0;return()=>((s=(s*1664525+1013904223)>>>0)/4294967296)}function buildMaze(seed){const R=rng(seed),g=Array.from({length:H},()=>Array(W).fill(1)),stack=[[1,H-2]];g[H-2][1]=0;const dirs=[[2,0],[-2,0],[0,2],[0,-2]];while(stack.length){const [x,y]=stack[stack.length-1],opts=[];for(const[dX,dY]of dirs){const nx=x+dX,ny=y+dY;if(nx>0&&ny>0&&nx<W-1&&ny<H-1&&g[ny][nx])opts.push([nx,ny,dX,dY])}if(!opts.length){stack.pop();continue}const o=opts[Math.floor(R()*opts.length)],nx=o[0],ny=o[1];g[y+o[3]/2][x+o[2]/2]=0;g[ny][nx]=0;stack.push([nx,ny])}g[1][W-2]=0;g[1][W-3]=0;return g}
function bfs(){const sx=1,sy=H-2,tx=W-2,ty=1,q=[[sx,sy]],prev=new Map(),key=(x,y)=>x+','+y;prev.set(key(sx,sy),null);while(q.length){const [x,y]=q.shift();if(x===tx&&y===ty)break;for(const[dX,dY]of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dX,ny=y+dY,k=key(nx,ny);if(nx>=0&&ny>=0&&nx<W&&ny<H&&!grid[ny][nx]&&!prev.has(k)){prev.set(k,[x,y]);q.push([nx,ny])}}}let cur=[tx,ty],out=[];while(cur){out.push(cur);cur=prev.get(key(cur[0],cur[1]))}return out.reverse()}
function cellWorld(x,y){return{x:(x-(W-1)/2)*1.05,z:(y-(H-1)/2)*1.05}}function rebuild(seed){while(world.children.length)world.remove(world.children[0]);grid=buildMaze(seed);path=bfs();const floor=new THREE.Mesh(new THREE.BoxGeometry(W*1.05,.25,H*1.05),mat(0xd8d0b4));floor.position.y=-.18;world.add(floor);const wm=mat(0x4a63a8);for(let y=0;y<H;y++)for(let x=0;x<W;x++)if(grid[y][x]){const p=cellWorld(x,y),m=new THREE.Mesh(new THREE.BoxGeometry(1.05,1.3,1.05),wm);m.position.set(p.x,.65,p.z);world.add(m)}const f=cellWorld(W-2,1),goal=new THREE.Mesh(new THREE.CylinderGeometry(.38,.38,.08,24),new THREE.MeshStandardMaterial({color:0x58e59f,emissive:0x31ff8c,emissiveIntensity:.7}));goal.position.set(f.x,.04,f.z);world.add(goal)}
function bean(i){return window.SkillArcadeCharacters?.make(THREE,i,{colors,scale:.72,compact:true,markerRadius:.55,labelY:1.34})||new THREE.Group()}
function passable(x,z){const gx=Math.round(x/1.05+(W-1)/2),gy=Math.round(z/1.05+(H-1)/2);return gx>=0&&gy>=0&&gx<W&&gy<H&&!grid[gy][gx]}function reset(){if(!mapName||state==='result'){const chosen=window.SkillArcadeMaps?.pick('maze-rush',MAZE_MAPS)||MAZE_MAPS[0];mapId=MAZE_MAPS.indexOf(chosen);mapName=chosen.name}const chosen=MAZE_MAPS[mapId];rebuild(chosen.seed);actors.clear();players=[];finishers=[];const s=cellWorld(1,H-2);for(let i=0;i<PLAYERS;i++){const g=bean(i);actors.add(g);players.push({id:i,name:names[i],g,pos:new THREE.Vector3(s.x+(i%4)*.12,.02,s.z+Math.floor(i/4)*.12),vel:new THREE.Vector3(),bot:i>0,pathIndex:0,finished:false,finishTime:0})}}
function update(p,dt){if(p.finished)return;let dx=0,dz=0;if(!p.bot){dx=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0);dz=(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0)}else{const wp=path[Math.min(path.length-1,p.pathIndex+1)],w=cellWorld(wp[0],wp[1]),vx=w.x-p.pos.x,vz=w.z-p.pos.z,d=Math.hypot(vx,vz)||1;dx=vx/d;dz=vz/d;if(d<.28&&p.pathIndex<path.length-2)p.pathIndex++}const l=Math.hypot(dx,dz),sp=p.bot?3.2+(p.id%3)*.12:3.75;if(l>.05){dx/=l;dz/=l;const nx=p.pos.x+dx*sp*dt,nz=p.pos.z+dz*sp*dt;if(passable(nx,p.pos.z))p.pos.x=nx;if(passable(p.pos.x,nz))p.pos.z=nz;p.g.rotation.y=Math.atan2(dx,dz)}p.g.position.copy(p.pos);const f=cellWorld(W-2,1);if(Math.hypot(p.pos.x-f.x,p.pos.z-f.z)<.48){p.finished=true;p.finishTime=elapsed;finishers.push(p.id);if(p.id===0){toast(`#${finishers.length} FINISH`);settle(finishers.length,`Finished in ${p.finishTime.toFixed(2)}s.`)}else if(finishers.length>=3&&!players[0].finished)settle(rank().findIndex(x=>x.id===0)+1,'The paid places are filled.')}}
function rank(){const f=cellWorld(W-2,1);return players.slice().sort((a,b)=>{if(a.finished!==b.finished)return a.finished?-1:1;if(a.finished)return a.finishTime-b.finishTime;return Math.hypot(a.pos.x-f.x,a.pos.z-f.z)-Math.hypot(b.pos.x-f.x,b.pos.z-f.z)})}
function board(){const r=rank(),place=r.findIndex(p=>p.id===0)+1;$('metric1').textContent=`#${place}`;$('metric2').textContent=mapName;$('leaderboard').innerHTML=r.map((p,i)=>`<div class="lb-row ${p.id===0?'you':''}"><b>${i+1}</b><span>${p.name}</span><span>${p.finished?p.finishTime.toFixed(1)+'s':'RACING'}</span></div>`).join('');$('walletValue').textContent=money(wallet)}
function settle(place,reason){if(finished)return;finished=true;state='result';const prize=place<=3?PAYOUTS[place-1]:0;wallet+=prize;account.totalPrizes=(account.totalPrizes||0)+prize;if(place===1)account.wins=(account.wins||0)+1;account.totalMatches=(account.totalMatches||0)+1;account.matches=account.matches||[];account.matches.unshift({game:'maze-rush',gameName:'Maze Rush',place,prize,net:prize-ENTRY,lobby:ENTRY,mapName,detail:`${mapName}${players[0].finished?' · '+players[0].finishTime.toFixed(2)+'s':''}`});account.matches=account.matches.slice(0,50);save();$('resultPlace').textContent=`#${place}`;$('resultTitle').textContent=place<=3?'PODIUM FINISH':'FINISHED';$('resultReason').textContent=reason;$('resultEntry').textContent=`-${money(ENTRY)}`;$('resultPrize').textContent=`+${money(prize)}`;$('resultMetric').textContent=players[0].finished?`${players[0].finishTime.toFixed(2)}s`:'DNF';$('resultNet').textContent=signed(prize-ENTRY);$('resultWallet').textContent=money(wallet);$('playAgainBtn').textContent=wallet>=ENTRY?`PLAY AGAIN · ${money(ENTRY)}`:'BACK TO ARCADE';$('leaveBtn').classList.add('hidden');setTimeout(()=>{$('overlay').classList.add('show');$('menuPanel').classList.add('hidden');$('resultPanel').classList.remove('hidden')},220)}
function begin(){if(wallet<ENTRY)return;wallet-=ENTRY;save();economy();reset();time=ROUND;count=3;elapsed=0;finished=false;state='countdown';$('overlay').classList.remove('show');$('menuPanel').classList.add('hidden');$('resultPanel').classList.add('hidden');$('countdown').classList.remove('hidden');$('leaveBtn').classList.remove('hidden')}
function forfeit(){if(!['play','countdown'].includes(state))return;account.totalMatches=(account.totalMatches||0)+1;account.matches.unshift({game:'maze-rush',gameName:'Maze Rush',mapName,forfeit:true,net:-ENTRY,lobby:ENTRY,detail:`${mapName} · Match left`});save();location.href='../../index.html'}
function step(dt){if(state==='countdown'){count-=dt;$('countdownNumber').textContent=String(Math.max(1,Math.ceil(count)));if(count<=0){state='play';$('countdown').classList.add('hidden');toast(`FIND THE EXIT · ${mapName}`)}}if(state==='play'){elapsed+=dt;time=Math.max(0,time-dt);for(const p of players)update(p,dt);if(time<=0&&!finished)settle(rank().findIndex(x=>x.id===0)+1,'Time expired.')}}
function frame(n){const dt=Math.min(.05,(n-last)/1000||0);last=n;acc+=dt;while(acc>=FIXED){step(FIXED);acc-=FIXED}if(toastT>0){toastT-=dt;if(toastT<=0)$('toast').classList.remove('show')}camera.position.set(players[0].pos.x,13,players[0].pos.z+7);camera.lookAt(players[0].pos.x,0,players[0].pos.z);board();renderer.render(scene,camera);requestAnimationFrame(frame)}
$('actionTouch').classList.add('hidden');reset();
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space')e.preventDefault()});addEventListener('keyup',e=>keys.delete(e.code));document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>{e.preventDefault();keys.add(k)};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>keys.delete(k)});$('startBtn').onclick=begin;$('playAgainBtn').onclick=()=>wallet>=ENTRY?begin():location.href='../../index.html';$('leaveBtn').onclick=forfeit;economy();board();requestAnimationFrame(frame);
})();