(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const canvas=$('game'), overlay=$('overlay'), menuPanel=$('menuPanel'), resultPanel=$('resultPanel');
  const startBtn=$('startBtn'), playAgainBtn=$('playAgainBtn'), leaveBtn=$('leaveBtn');
  const walletValue=$('walletValue'), lobbyWallet=$('lobbyWallet'), positionValue=$('positionValue'), timeValue=$('timeValue'), checkpointValue=$('checkpointValue');
  const leaderboard=$('leaderboard'), toast=$('toast'), countdown=$('countdown'), countdownNumber=$('countdownNumber');
  const finishBanner=$('finishBanner'), finishPlace=$('finishPlace');
  const resultPlace=$('resultPlace'), resultTitle=$('resultTitle'), resultReason=$('resultReason'), resultEntry=$('resultEntry'), resultPrize=$('resultPrize'), resultNet=$('resultNet'), resultWallet=$('resultWallet');
  const entryValue=$('entryValue'), poolValue=$('poolValue'), p1=$('p1'), p2=$('p2'), p3=$('p3'), entryMessage=$('entryMessage'), jumpTouch=$('jumpTouch');
  const mapNameEls=[...document.querySelectorAll('[data-map-name]')];
  if(!window.THREE){startBtn.disabled=true;startBtn.textContent='3D ENGINE FAILED TO LOAD';return;}
  const THREE=window.THREE;
  const qs=new URLSearchParams(location.search); const req=Number(qs.get('entry')); const ENTRY=[1,5,20].includes(req)?req:1;
  const STORAGE_KEY='skillArcadeDemoAccountV1', MAP_KEY='skillArcadeLastSprintMapV1';
  const DEMO_BALANCE=25, PLAYERS=12, ROUND=150, FEE_RATE=.05, PAYOUT_RATIOS=[6,3.4,2], PAYOUTS=PAYOUT_RATIOS.map(v=>v*ENTRY), PRIZE_POOL=PLAYERS*ENTRY*(1-FEE_RATE);
  const COURSE_W=16, FINISH_Z=165.12, GRAVITY=23, MAX_SPEED=6.55, GROUND_ACCEL=24, GROUND_BRAKE=32, AIR_ACCEL=10.5, JUMP_V=7.35, PLAYER_R=.36, FIXED=1/120;
  const names=['You','Nova','Mika','Rook','Volt','Pip','Zed','Kira','Atlas','Echo','Juno','Blaze'];
  const colors=[0xffd84e,0xff5f83,0x55d6b0,0x53c8ff,0x9f7cff,0xff8a4f,0x77dd67,0x42d1d6,0xffb347,0xe66cff,0x6f8cff,0xff6b57];
  const keys=new Set(), players=[], finishOrder=[];
  let state='menu', account=loadAccount(), wallet=account.wallet, roundTime=ROUND, countdownTime=3, elapsed=0, last=performance.now(), acc=0, toastTimer=0, activeRecorded=true, userFinished=false, jumpBuffer=0;
  let selectedMapIndex=0, selectedMap=null;
  const groundRects=[], obstacles=[];

  function money(v){return `$${Math.max(0,+v||0).toFixed(2)}`}
  function signed(v){v=+v||0;return `${v>=0?'+':'−'}$${Math.abs(v).toFixed(2)}`}
  function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
  function moveToward(v,t,d){return v<t?Math.min(v+d,t):v>t?Math.max(v-d,t):t}
  function loadAccount(){const f={wallet:DEMO_BALANCE,totalPrizes:0,wins:0,totalMatches:0,matches:[]};try{const r=localStorage.getItem(STORAGE_KEY);if(!r)return f;const d=JSON.parse(r);return{wallet:Number.isFinite(+d.wallet)?Math.max(0,+d.wallet):DEMO_BALANCE,totalPrizes:Number.isFinite(+d.totalPrizes)?Math.max(0,+d.totalPrizes):0,wins:Number.isFinite(+d.wins)?Math.max(0,+d.wins):0,totalMatches:Number.isFinite(+d.totalMatches)?Math.max(0,+d.totalMatches):0,matches:Array.isArray(d.matches)?d.matches:[]}}catch{return f}}
  function save(){account.wallet=Math.max(0,wallet);localStorage.setItem(STORAGE_KEY,JSON.stringify(account))}
  function record(place,prize,finishTime,forfeit=false){if(activeRecorded)return;activeRecorded=true;const net=(prize||0)-ENTRY;if(!forfeit){account.totalPrizes=(account.totalPrizes||0)+(prize||0);if(place===1)account.wins=(account.wins||0)+1}account.totalMatches=(account.totalMatches||0)+1;account.matches=account.matches||[];account.matches.unshift({game:'obstacle-sprint',gameName:'Obstacle Sprint',mapName:selectedMap?.name||'',place:forfeit?null:place,prize:+prize||0,net,forfeit:!!forfeit,finishTime:finishTime||null,lobby:ENTRY,detail:`${selectedMap?.name||'Course'}${finishTime?` · ${Number(finishTime).toFixed(2)}s`:''}`,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})});account.matches=account.matches.slice(0,50);save()}
  function updateEconomy(){entryValue.textContent=money(ENTRY);poolValue.textContent=money(PRIZE_POOL);p1.textContent=money(PAYOUTS[0]);p2.textContent=money(PAYOUTS[1]);p3.textContent=money(PAYOUTS[2]);lobbyWallet.textContent=money(wallet);walletValue.textContent=money(wallet);startBtn.textContent=wallet>=ENTRY?`ENTER MATCH · ${money(ENTRY)}`:'INSUFFICIENT DEMO BALANCE';startBtn.disabled=wallet<ENTRY;entryMessage.textContent=wallet>=ENTRY?'Demo entry is deducted when the match starts.':'Return to the arcade and reset the demo wallet.'}

  const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;if('outputColorSpace'in renderer)renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x74cffa);scene.fog=new THREE.Fog(0x74cffa,58,170);
  const camera=new THREE.PerspectiveCamera(62,1,.05,220);scene.add(camera);
  scene.add(new THREE.HemisphereLight(0xd9f4ff,0x42405f,1.65)); const sun=new THREE.DirectionalLight(0xffffff,2);sun.position.set(-18,35,-20);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-22;sun.shadow.camera.right=22;sun.shadow.camera.top=45;sun.shadow.camera.bottom=-10;scene.add(sun);
  const world=new THREE.Group(), playerRoot=new THREE.Group();scene.add(world,playerRoot);
  const mats={course:new THREE.MeshStandardMaterial({color:0x7658a8,roughness:.7}),edge:new THREE.MeshStandardMaterial({color:0x4b3778,roughness:.75}),yellow:new THREE.MeshStandardMaterial({color:0xffcf43,roughness:.55}),pink:new THREE.MeshStandardMaterial({color:0xff6e9d,roughness:.55}),cyan:new THREE.MeshStandardMaterial({color:0x52d6e8,roughness:.55}),green:new THREE.MeshStandardMaterial({color:0x68dca8,roughness:.55}),white:new THREE.MeshStandardMaterial({color:0xf4f8fb,roughness:.65}),dark:new THREE.MeshStandardMaterial({color:0x263044,roughness:.7}),orange:new THREE.MeshStandardMaterial({color:0xff8a55,roughness:.55})};
  const matByName=n=>mats[n]||mats.course;
  function box(w,h,d,x,y,z,mat=mats.course){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.receiveShadow=true;m.castShadow=true;world.add(m);return m}
  function platform(x,z,w,d,mat='course'){box(w,.5,d,x,-.25,z,matByName(mat));groundRects.push({x,z,w,d})}
  function rail(z,d){box(.28,1.25,d,-COURSE_W/2-.15,.38,z,mats.edge);box(.28,1.25,d,COURSE_W/2+.15,.38,z,mats.edge)}
  function addSweeper(z,speed,phase=0,mat='yellow',len=10.2){const pivot=new THREE.Group();pivot.position.set(0,.62,z);const bar=new THREE.Mesh(new THREE.BoxGeometry(len,.5,.5),matByName(mat));bar.castShadow=bar.receiveShadow=true;pivot.add(bar);world.add(pivot);obstacles.push({type:'sweeper',z,speed,phase,pivot,len,halfWidth:.25,top:.87,angle:phase})}
  function addGate(z,gapW=2.9,speed=.92,phase=0,mat='green'){const o={type:'gate',z,gapW,gapX:0,depth:.65,height:2,speed,phase,left:null,right:null};o.left=box(1,o.height,o.depth,-3.65,1,z,matByName(mat));o.right=box(1,o.height,o.depth,3.65,1,z,matByName(mat));obstacles.push(o)}
  function addPusher(z,phase=0,mat='pink',speed=1.28,travel=4.05){const o={type:'pusher',z,phase,x:0,halfX:1.05,halfZ:1.05,top:1.8,speed,travel,mesh:box(2.1,1.8,2.1,0,.9,z,matByName(mat))};obstacles.push(o)}
  function finishArch(){for(let i=-5;i<=5;i++){box(.9,.05,.7,i,.04,-2.5,(i+5)%2?mats.white:mats.dark);box(.9,.05,.7,i,.04,FINISH_Z,(i+5)%2?mats.white:mats.dark)}box(.55,4,.55,-5.4,2,FINISH_Z+1,mats.yellow);box(.55,4,.55,5.4,2,FINISH_Z+1,mats.yellow);box(11.3,.55,.55,0,4,FINISH_Z+1,mats.yellow)}

  const MAPS=[
    {name:'Skyline Run',sky:0x74cffa,fog:0x74cffa,platforms:[{x:0,z:17,w:12,d:44},{x:-1.8,z:41,w:5.2,d:4,mat:'pink'},{x:1.8,z:47.5,w:5.2,d:4,mat:'cyan'},{x:-1.8,z:54,w:5.2,d:4,mat:'pink'},{x:1.8,z:60.5,w:5.2,d:4,mat:'cyan'},{x:0,z:99,w:12,d:69}],rails:[{z:17,d:44},{z:99,d:69}],sweepers:[[14,1.65,.2,'yellow'],[24,-1.8,1.3,'pink'],[73,1.95,.7,'cyan'],[84,-2.15,2.1,'yellow'],[116,2.25,.1,'pink'],[123,-2.35,1.6,'cyan']],gates:[[32,2.9,.92,0,'green']],pushers:[[96,0,'pink'],[101,1.9,'yellow'],[106,3.8,'pink']],jumpZones:[[36.5,40.5],[43.5,47],[50,53.5],[56.5,60]],checkpoints:[[-3,0],[35,0],[65,0],[91,0],[110,0]],path:[[-3,0],[34,0],[41,-1.8],[47.5,1.8],[54,-1.8],[60.5,1.8],[68,0],[92,0],[112,0],[129,0]]},
    {name:'Spinner Alley',sky:0x8bd5ff,fog:0x8bd5ff,platforms:[{x:0,z:64,w:12,d:138,mat:'cyan'}],rails:[{z:64,d:138}],sweepers:[[14,2.05,.2,'yellow'],[23,-2.3,1.1,'pink'],[36,2.4,.5,'orange'],[49,-2.15,2.3,'cyan'],[67,2.55,.9,'yellow'],[82,-2.3,1.9,'pink'],[100,2.6,.1,'cyan'],[119,-2.65,1.3,'orange']],gates:[[57,2.6,1.12,.4,'green'],[91,2.5,1.25,1.7,'pink']],pushers:[[108,0,'yellow',1.5,4.2],[114,2.2,'pink',1.4,4.2]],jumpZones:[],checkpoints:[[-3,0],[30,0],[60,0],[90,0],[112,0]],path:[[-3,0],[25,-2],[45,2],[65,-2],[85,2],[105,-2],[129,0]]},
    {name:'Island Leap',sky:0x91e7d1,fog:0x91e7d1,platforms:[{x:0,z:11,w:12,d:34,mat:'green'},{x:-2.4,z:34,w:5,d:4,mat:'pink'},{x:2.4,z:40.5,w:5,d:4,mat:'cyan'},{x:-2.4,z:47,w:5,d:4,mat:'yellow'},{x:2.4,z:53.5,w:5,d:4,mat:'pink'},{x:-2.4,z:60,w:5,d:4,mat:'cyan'},{x:2.4,z:66.5,w:5,d:4,mat:'yellow'},{x:0,z:101,w:12,d:65,mat:'course'}],rails:[{z:11,d:34},{z:101,d:65}],sweepers:[[17,1.85,.1,'yellow'],[78,-2,.8,'pink'],[89,2.15,2.2,'cyan'],[106,-2.25,.4,'orange'],[120,2.4,1.6,'yellow']],gates:[[26,3,1.05,0,'green'],[96,2.7,1.2,1.1,'pink']],pushers:[[113,.6,'cyan',1.35,4]],jumpZones:[[28.5,33.5],[36,40],[42.5,46.5],[49,53],[55.5,59.5],[62,66]],checkpoints:[[-3,0],[28,0],[70,0],[93,0],[112,0]],path:[[-3,0],[27,0],[34,-2.4],[40.5,2.4],[47,-2.4],[53.5,2.4],[60,-2.4],[66.5,2.4],[72,0],[95,0],[112,0],[129,0]]},
    {name:'Neon Gauntlet',sky:0x735cb9,fog:0x735cb9,platforms:[{x:0,z:17,w:12,d:44,mat:'course'},{x:-2,z:45,w:6,d:5,mat:'pink'},{x:2,z:52,w:6,d:5,mat:'cyan'},{x:-2,z:59,w:6,d:5,mat:'orange'},{x:2,z:66,w:6,d:5,mat:'green'},{x:0,z:102,w:12,d:62,mat:'dark'}],rails:[{z:17,d:44},{z:102,d:62}],sweepers:[[27,2.1,.4,'orange'],[79,-2.35,.7,'cyan'],[92,2.5,1.4,'pink'],[104,-2.45,.3,'yellow'],[122,2.7,1.9,'cyan']],gates:[[16,2.7,1.15,0,'green'],[35,2.6,1.3,1.4,'pink'],[84,2.5,1.15,2.2,'cyan']],pushers:[[111,.2,'orange',1.45,4.1],[117,2,'pink',1.6,4.1]],jumpZones:[[38.5,44.5],[47.5,51.5],[54.5,58.5],[61.5,65.5]],checkpoints:[[-3,0],[38,0],[72,0],[98,0],[116,0]],path:[[-3,0],[37,0],[45,-2],[52,2],[59,-2],[66,2],[73,0],[98,0],[116,0],[129,0]]},
    {name:'Gate Rush',sky:0x9bd6ff,fog:0x9bd6ff,platforms:[{x:0,z:64,w:12,d:138,mat:'green'}],rails:[{z:64,d:138}],sweepers:[[20,1.9,.2,'yellow'],[64,-2.15,1.1,'cyan'],[103,2.35,.5,'pink'],[121,-2.45,1.8,'orange']],gates:[[12,2.5,1.1,0,'pink'],[35,2.35,1.25,1.2,'cyan'],[52,2.2,1.35,2.1,'yellow'],[78,2.25,1.4,.6,'green'],[94,2.15,1.5,2.7,'pink'],[114,2.1,1.6,1.5,'cyan']],pushers:[[87,.5,'orange',1.45,4.1]],jumpZones:[],checkpoints:[[-3,0],[30,0],[60,0],[90,0],[112,0]],path:[[-3,0],[25,0],[48,-1.5],[72,1.5],[96,-1.5],[116,1.5],[129,0]]},
    {name:'Pusher Plaza',sky:0xffd0ba,fog:0xffd0ba,platforms:[{x:0,z:64,w:12,d:138,mat:'orange'}],rails:[{z:64,d:138}],sweepers:[[18,1.8,.4,'cyan'],[70,-2.1,1.4,'yellow'],[124,2.45,.7,'pink']],gates:[[42,2.8,1.0,.8,'green'],[101,2.5,1.2,2.2,'cyan']],pushers:[[28,.1,'pink',1.35,4.2],[34,1.8,'yellow',1.5,4.2],[55,.8,'cyan',1.45,4.15],[82,2.4,'pink',1.55,4.15],[89,.3,'orange',1.6,4.1],[110,1.2,'yellow',1.5,4.1]],jumpZones:[],checkpoints:[[-3,0],[30,0],[60,0],[90,0],[112,0]],path:[[-3,0],[26,2],[40,-2],[58,2],[78,-2],[98,2],[116,-1],[129,0]]},
    {name:'Turbo Turnpike',sky:0xb8e9ff,fog:0xb8e9ff,platforms:[{x:0,z:20,w:12,d:50,mat:'cyan'},{x:-2.6,z:50,w:5,d:5,mat:'yellow'},{x:2.6,z:57,w:5,d:5,mat:'pink'},{x:-2.6,z:64,w:5,d:5,mat:'green'},{x:2.6,z:71,w:5,d:5,mat:'orange'},{x:0,z:103,w:12,d:58,mat:'course'}],rails:[{z:20,d:50},{z:103,d:58}],sweepers:[[16,2.15,.1,'pink'],[31,-2.35,1.7,'yellow'],[83,2.4,.8,'cyan'],[97,-2.5,2.0,'orange'],[119,2.65,.3,'green']],gates:[[39,2.6,1.2,.7,'green'],[108,2.4,1.3,1.9,'pink']],pushers:[[91,.4,'yellow',1.45,4.1]],jumpZones:[[45,49.5],[52.5,56.5],[59.5,63.5],[66.5,70.5]],checkpoints:[[-3,0],[42,0],[76,0],[100,0],[115,0]],path:[[-3,0],[42,0],[50,-2.6],[57,2.6],[64,-2.6],[71,2.6],[77,0],[100,0],[116,0],[129,0]]},
    {name:'Final Frenzy',sky:0xd7b9ff,fog:0xd7b9ff,platforms:[{x:0,z:64,w:12,d:138,mat:'dark'}],rails:[{z:64,d:138}],sweepers:[[15,2.4,.2,'orange'],[26,-2.55,1.2,'pink'],[44,2.65,.8,'cyan'],[62,-2.75,2.0,'yellow'],[81,2.8,.4,'green'],[99,-2.9,1.6,'pink'],[121,3.0,.9,'cyan']],gates:[[34,2.45,1.2,.4,'green'],[72,2.3,1.35,1.9,'orange'],[110,2.2,1.5,2.6,'yellow']],pushers:[[52,.3,'pink',1.55,4.2],[90,2.1,'cyan',1.6,4.2]],jumpZones:[],checkpoints:[[-3,0],[30,0],[60,0],[90,0],[112,0]],path:[[-3,0],[28,-2],[48,2],[68,-2],[88,2],[108,-2],[129,0]]}
  ];

  function scaledMap(m){const sx=1.22,sz=1.28;return{...m,platforms:m.platforms.map(p=>({...p,x:p.x*sx,z:p.z*sz,w:p.w*sx,d:p.d*sz})),rails:m.rails.map(r=>({...r,z:r.z*sz,d:r.d*sz})),sweepers:m.sweepers.map(a=>{const q=[a[0]*sz,a[1],a[2],a[3]];if(a.length>4)q[4]=a[4]*sx;return q}),gates:m.gates.map(a=>[a[0]*sz,a[1]*sx,a[2],a[3],a[4]]),pushers:m.pushers.map(a=>{const q=[a[0]*sz,a[1],a[2]];if(a.length>3)q[3]=a[3];if(a.length>4)q[4]=a[4]*sx;return q}),jumpZones:m.jumpZones.map(a=>[a[0]*sz,a[1]*sz]),checkpoints:m.checkpoints.map(a=>[a[0]*sz,a[1]*sx]),path:m.path.map(a=>[a[0]*sz,a[1]*sx])}}
  function chooseNewMap(){let lastIndex=Number(localStorage.getItem(MAP_KEY));if(!Number.isInteger(lastIndex)||lastIndex<0||lastIndex>=MAPS.length)lastIndex=-1;let choices=MAPS.map((_,i)=>i).filter(i=>i!==lastIndex);selectedMapIndex=choices[Math.floor(Math.random()*choices.length)];selectedMap=scaledMap(MAPS[selectedMapIndex]);localStorage.setItem(MAP_KEY,String(selectedMapIndex));mapNameEls.forEach(e=>e.textContent=selectedMap.name)}
  function buildMap(){world.clear();groundRects.length=0;obstacles.length=0;scene.background=new THREE.Color(selectedMap.sky);scene.fog.color.setHex(selectedMap.fog);for(const p of selectedMap.platforms)platform(p.x,p.z,p.w,p.d,p.mat);for(const r of selectedMap.rails)rail(r.z,r.d);for(const s of selectedMap.sweepers)addSweeper(...s);for(const g of selectedMap.gates)addGate(...g);for(const p of selectedMap.pushers)addPusher(...p);finishArch();for(const [x,y,z,s] of [[-16,8,18,4],[18,10,48,5],[-19,9,78,4],[20,12,110,5]]){const c=new THREE.Mesh(new THREE.SphereGeometry(s,16,10),new THREE.MeshStandardMaterial({color:0xf4fbff,roughness:1}));c.position.set(x,y,z);world.add(c)}}
  chooseNewMap();buildMap();

  function makeRunnerModel(i){return window.SkillArcadeCharacters?.make(THREE,i,{colors,scale:1.02,markerRadius:.72,labelY:2.12})||new THREE.Group()}
  function startPoint(i){const lane=-5.7+(i%4)*3.8,row=Math.floor(i/4);return new THREE.Vector3(lane,.05,-4-row*1.55)}
  function createPlayer(i){const group=makeRunnerModel(i);playerRoot.add(group);const sp=startPoint(i);return{id:i,name:names[i],group,pos:sp.clone(),vel:new THREE.Vector3(),grounded:true,coyote:.12,checkpoint:sp.clone(),checkpointIndex:1,finished:false,finishTime:null,respawn:0,hitCooldown:0,bot:i>0,skill:i===0?1:[.88,.91,.84,.95,.86,.9,.89,.93,.87,.92,.9][(i-1)%11],laneBias:[0,-2.6,2.7,-1.3,1.5,-3.7,3.8,.4,-2,2,0,-.7][i%12],animPhase:i*.7}}
  function resetPlayers(){playerRoot.clear();players.length=0;finishOrder.length=0;for(let i=0;i<PLAYERS;i++)players.push(createPlayer(i));userFinished=false;finishBanner.classList.add('hidden')}
  resetPlayers();
  function groundAt(pos){for(const r of groundRects){if(Math.abs(pos.x-r.x)<=r.w/2+.06&&Math.abs(pos.z-r.z)<=r.d/2+.06)return 0}return null}
  function checkpointFor(z,x){let best={idx:1,z:selectedMap.checkpoints[0][0],x:selectedMap.checkpoints[0][1]};for(let i=0;i<selectedMap.checkpoints.length;i++){const cp=selectedMap.checkpoints[i];if(z>=cp[0])best={idx:i+1,z:cp[0],x:cp[1]}}return{idx:best.idx,z:best.z,x:clamp(x+best.x*.35,-6,6)}}
  function respawnPlayer(p){const c=checkpointFor(p.checkpoint.z,p.checkpoint.x);p.pos.set(c.x,.05,c.z);p.vel.set(0,0,0);p.respawn=0;p.hitCooldown=.55;p.coyote=.12;p.group.visible=true}
  function knock(p,dx,dz,power=6.2,up=3.2){const l=Math.hypot(dx,dz)||1;p.vel.x+=(dx/l)*power;p.vel.z+=(dz/l)*power;p.vel.y=Math.max(p.vel.y,up);p.grounded=false}
  function segmentHitSweeper(p,o){if(p.finished||p.respawn>0||p.hitCooldown>0||p.pos.y>o.top+.04)return;const a=o.angle,dirX=Math.cos(a),dirZ=-Math.sin(a),sideX=-dirZ,sideZ=dirX,relX=p.pos.x,relZ=p.pos.z-o.z,along=relX*dirX+relZ*dirZ,across=relX*sideX+relZ*sideZ;if(Math.abs(along)<=o.len/2+PLAYER_R&&Math.abs(across)<=o.halfWidth+PLAYER_R){const side=across===0?1:Math.sign(across);knock(p,sideX*side,sideZ*side,6.5,3.15);p.hitCooldown=.3}}
  function updateObstacles(){for(const o of obstacles){if(o.type==='sweeper'){o.angle=elapsed*o.speed+o.phase;o.pivot.rotation.y=o.angle}else if(o.type==='gate'){o.gapX=Math.sin(elapsed*o.speed+o.phase)*2.95;const left=-COURSE_W/2,right=COURSE_W/2,gL=o.gapX-o.gapW/2,gR=o.gapX+o.gapW/2,lw=Math.max(.1,gL-left),rw=Math.max(.1,right-gR);o.left.scale.x=lw;o.left.position.x=left+lw/2;o.right.scale.x=rw;o.right.position.x=gR+rw/2}else if(o.type==='pusher'){o.x=Math.sin(elapsed*o.speed+o.phase)*o.travel;o.mesh.position.x=o.x}}}
  function collideObstacles(p){if(p.finished||p.respawn>0)return;for(const o of obstacles){if(o.type==='sweeper'){segmentHitSweeper(p,o);continue}if(o.type==='gate'){const zHit=Math.abs(p.pos.z-o.z)<=o.depth/2+PLAYER_R,vertical=p.pos.y<o.height+.02,safe=p.pos.x-PLAYER_R>=o.gapX-o.gapW/2&&p.pos.x+PLAYER_R<=o.gapX+o.gapW/2;if(zHit&&vertical&&!safe){p.pos.z=o.z-(p.vel.z>=0?o.depth/2+PLAYER_R+.02:-(o.depth/2+PLAYER_R+.02));p.vel.z=Math.min(p.vel.z,-1.3)}continue}if(o.type==='pusher'&&p.hitCooldown<=0){const hx=Math.abs(p.pos.x-o.x)<=o.halfX+PLAYER_R,hz=Math.abs(p.pos.z-o.z)<=o.halfZ+PLAYER_R,hy=p.pos.y<o.top+.02;if(hx&&hz&&hy){knock(p,p.pos.x-o.x||.1,p.pos.z-o.z||-.25,6.8,2.85);p.hitCooldown=.34}}}}
  function botInput(p){let tx=p.laneBias,jump=false,z=p.pos.z;const future=selectedMap.path.find(pt=>pt[0]>z+1.4);if(future)tx=future[1];for(const o of obstacles){if(o.type==='gate'&&Math.abs(o.z-z)<7)tx=o.gapX;else if(o.type==='pusher'&&Math.abs(o.z-z)<5)tx=o.x>0?-3.4:3.4;else if(o.type==='sweeper'&&o.z-z>0&&o.z-z<2.8&&p.grounded&&Math.sin(elapsed*2+p.id)>-.1)jump=true}for(const j of selectedMap.jumpZones){if(z>=j[0]&&z<=j[1]&&p.grounded)jump=true}return{x:clamp((tx-p.pos.x)*.62,-1,1),z:1,jump}}
  function userInput(){return{x:(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),z:(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),jump:false}}
  function animateRunner(p){const l=p.group.userData.limbs;if(!l)return;const speed=Math.hypot(p.vel.x,p.vel.z),running=p.grounded&&speed>.35,phase=elapsed*(7.5+speed*.45)+p.animPhase,swing=running?Math.sin(phase)*.65:0;l.leftArm.rotation.x=swing;l.rightArm.rotation.x=-swing;l.leftLeg.rotation.x=-swing*.78;l.rightLeg.rotation.x=swing*.78;l.body.position.y=.82+(running?Math.abs(Math.sin(phase*2))*.035:0);l.head.position.y=1.38+(running?Math.abs(Math.sin(phase*2))*.025:0)}
  function updatePlayer(p,dt){p.hitCooldown=Math.max(0,p.hitCooldown-dt);if(p.finished){p.vel.x*=Math.pow(.05,dt);p.vel.z*=Math.pow(.05,dt);animateRunner(p);return}if(p.respawn>0){p.respawn-=dt;p.group.visible=false;if(p.respawn<=0)respawnPlayer(p);return}const input=p.bot?botInput(p):userInput();if(!p.bot&&jumpBuffer>0)input.jump=true;let len=Math.hypot(input.x,input.z);if(len>1){input.x/=len;input.z/=len;len=1}if(p.grounded)p.coyote=.12;else p.coyote=Math.max(0,p.coyote-dt);const scale=p.hitCooldown>0?.35:1,targetX=input.x*MAX_SPEED*(p.bot?p.skill:1),targetZ=input.z*MAX_SPEED*(p.bot?p.skill:1);if(len>.01){const a=(p.grounded?GROUND_ACCEL:AIR_ACCEL)*scale;p.vel.x=moveToward(p.vel.x,targetX,a*dt);p.vel.z=moveToward(p.vel.z,targetZ,a*dt)}else if(p.grounded){p.vel.x=moveToward(p.vel.x,0,GROUND_BRAKE*dt);p.vel.z=moveToward(p.vel.z,0,GROUND_BRAKE*dt)}if(input.jump&&(p.grounded||p.coyote>0)){p.vel.y=JUMP_V;p.grounded=false;p.coyote=0;if(!p.bot)jumpBuffer=0}p.vel.y-=GRAVITY*dt;p.pos.addScaledVector(p.vel,dt);collideObstacles(p);const g=groundAt(p.pos);if(g!==null&&p.pos.y<=g+.08&&p.vel.y<=0){p.pos.y=g+.05;p.vel.y=0;p.grounded=true}else if(g===null||p.pos.y>g+.1)p.grounded=false;p.pos.x=clamp(p.pos.x,-COURSE_W/2+.35,COURSE_W/2-.35);const cp=checkpointFor(p.pos.z,p.pos.x);if(cp.idx>p.checkpointIndex){p.checkpointIndex=cp.idx;p.checkpoint.set(cp.x,.05,cp.z);if(!p.bot)showToast(`CHECKPOINT ${cp.idx}/5`)}if(p.pos.y<-7){p.respawn=.68;p.vel.set(0,0,0);if(!p.bot)showToast('RESPAWNING…')}if(p.pos.z>=FINISH_Z&&!p.finished){p.finished=true;p.finishTime=ROUND-roundTime;finishOrder.push(p.id);p.vel.set(0,0,0);const place=finishOrder.length;if(!p.bot){userFinished=true;finishPlace.textContent=`#${place}`;finishBanner.classList.remove('hidden');showToast(place<=3?`PODIUM #${place}`:`FINISHED #${place}`)}if(finishOrder.length>=3)endMatch('podium')}const hs=Math.hypot(p.vel.x,p.vel.z);if(hs>.2){const face=Math.atan2(p.vel.x,p.vel.z);let d=face-p.group.rotation.y;while(d>Math.PI)d-=Math.PI*2;while(d<-Math.PI)d+=Math.PI*2;p.group.rotation.y+=d*Math.min(1,dt*12)}p.group.position.copy(p.pos);animateRunner(p)}
  function playerCollisions(){for(let i=0;i<players.length;i++)for(let j=i+1;j<players.length;j++){const a=players[i],b=players[j];if(a.finished||b.finished||a.respawn>0||b.respawn>0)continue;const dx=b.pos.x-a.pos.x,dz=b.pos.z-a.pos.z,d=Math.hypot(dx,dz),min=.64;if(d>0&&d<min){const nx=dx/d,nz=dz/d,push=(min-d)*.32;a.pos.x-=nx*push;a.pos.z-=nz*push;b.pos.x+=nx*push;b.pos.z+=nz*push}}}
  function ranking(){return players.slice().sort((a,b)=>{if(a.finished&&b.finished)return a.finishTime-b.finishTime;if(a.finished)return-1;if(b.finished)return 1;if(b.checkpointIndex!==a.checkpointIndex)return b.checkpointIndex-a.checkpointIndex;return b.pos.z-a.pos.z})}
  function positionOf(id){return ranking().findIndex(p=>p.id===id)+1}
  function updateCamera(dt){let target=players[0];if(userFinished){const n=ranking().find(p=>!p.finished);if(n)target=n}const desired=new THREE.Vector3(target.pos.x,target.pos.y+3.15,target.pos.z-5.7),follow=1-Math.pow(.00045,dt);camera.position.lerp(desired,follow);camera.lookAt(new THREE.Vector3(target.pos.x,target.pos.y+.92,target.pos.z+3.2))}
  function renderLeaderboard(){const r=ranking();leaderboard.innerHTML=r.map((p,i)=>`<div class="lb-row ${p.id===0?'you':''}"><b>${i+1}</b><span>${p.name}</span><span>${p.finished?`${p.finishTime.toFixed(1)}s`:`${Math.max(0,Math.min(99,Math.round((p.pos.z+5)/(FINISH_Z+5)*100)))}%`}</span></div>`).join('');positionValue.textContent=`${positionOf(0)} / ${PLAYERS}`;checkpointValue.textContent=`${players[0].checkpointIndex} / 5`}
  function showToast(msg){toast.textContent=msg;toast.classList.add('show');toastTimer=1.1}
  function begin(){if(wallet+1e-9<ENTRY)return;wallet-=ENTRY;save();updateEconomy();activeRecorded=false;jumpBuffer=0;keys.clear();resetPlayers();roundTime=ROUND;countdownTime=3;elapsed=0;acc=0;state='countdown';overlay.classList.remove('show');menuPanel.classList.add('hidden');resultPanel.classList.add('hidden');countdown.classList.remove('hidden');countdownNumber.textContent='3';leaveBtn.classList.remove('hidden')}
  function endMatch(reason){if(state==='result'||state==='menu')return;state='result';const r=ranking(),place=r.findIndex(p=>p.id===0)+1,prize=place<=3?PAYOUTS[place-1]:0;wallet+=prize;record(place,prize,players[0].finishTime,false);save();walletValue.textContent=money(wallet);resultPlace.textContent=`#${place}`;resultTitle.textContent=place<=3?'PODIUM FINISH':'RACE COMPLETE';resultReason.textContent=place===1?`You won ${selectedMap.name}.`:place<=3?`Paid finish on ${selectedMap.name}.`:reason==='time'?'Time expired before you reached the podium.':'The podium was filled before you finished.';resultEntry.textContent=`−${money(ENTRY)}`;resultPrize.textContent=`+${money(prize)}`;resultNet.textContent=signed(prize-ENTRY);resultWallet.textContent=money(wallet);playAgainBtn.textContent=wallet>=ENTRY?`NEW MAP · ${money(ENTRY)}`:'BACK TO ARCADE';playAgainBtn.disabled=false;finishBanner.classList.add('hidden');leaveBtn.classList.add('hidden');setTimeout(()=>{overlay.classList.add('show');menuPanel.classList.add('hidden');resultPanel.classList.remove('hidden')},350)}
  function forfeit(){if(!['play','countdown'].includes(state))return;record(null,0,null,true);state='menu';location.href='../../index.html'}
  function step(dt){jumpBuffer=Math.max(0,jumpBuffer-dt);if(state==='countdown'){countdownTime-=dt;if(countdownTime<=0){state='play';countdown.classList.add('hidden');showToast('GO!')}else countdownNumber.textContent=String(Math.ceil(countdownTime));updateObstacles()}if(state==='play'){elapsed+=dt;roundTime=Math.max(0,roundTime-dt);updateObstacles();for(const p of players)updatePlayer(p,dt);playerCollisions();if(roundTime<=0)endMatch('time')}}
  function frame(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;acc+=dt;while(acc>=FIXED){step(FIXED);acc-=FIXED}if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)toast.classList.remove('show')}updateCamera(dt);renderLeaderboard();timeValue.textContent=`${Math.floor(roundTime/60)}:${String(Math.ceil(roundTime%60)).padStart(2,'0')}`;walletValue.textContent=money(wallet);renderer.render(scene,camera);requestAnimationFrame(frame)}
  function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
  addEventListener('resize',resize);resize();addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space'){e.preventDefault();jumpBuffer=.14}});addEventListener('keyup',e=>keys.delete(e.code));
  startBtn.addEventListener('click',begin);playAgainBtn.addEventListener('click',()=>{if(wallet<ENTRY){location.href='../../index.html';return}chooseNewMap();buildMap();resultPanel.classList.add('hidden');overlay.classList.remove('show');begin()});leaveBtn.addEventListener('click',forfeit);
  document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.addEventListener('pointerdown',e=>{e.preventDefault();keys.add(k);b.setPointerCapture?.(e.pointerId)});for(const ev of ['pointerup','pointercancel','pointerleave'])b.addEventListener(ev,()=>keys.delete(k))});jumpTouch.addEventListener('pointerdown',e=>{e.preventDefault();jumpBuffer=.14});
  updateEconomy();renderLeaderboard();requestAnimationFrame(frame);
})();
