import http from 'node:http';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import {WebSocketServer} from 'ws';
import {config,publicConfig} from './config.js';
import {requireUser} from './auth.js';
import {supabaseAdmin} from './supabase.js';
import {provisionEmbeddedWallet,requestEmbeddedTransfer} from './wallet-provider.js';
import {normalizeAddress,tokenBalance,createEscrowMatch,buildEntryTransactions,verifyEntryLocked} from './chain.js';
import {joinMatch,leaveMatch,issueServerTicket,consumeServerTicket} from './matchmaker.js';

const app=express();app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false}));app.use(cors({origin:config.publicOrigin==='*'?true:config.publicOrigin,credentials:false}));app.use(express.json({limit:'128kb'}));
app.get('/health',(_req,res)=>res.json({ok:true,service:'skill-arcade-live',version:'6.6.0',environment:config.environment}));
app.get('/api/config',(_req,res)=>res.json(publicConfig()));

app.use('/api',requireUser);
app.get('/api/session',(req,res)=>res.json({user:{id:req.user.id,email:req.user.email}}));
async function getOrCreateEmbeddedWallet(user){
  const sb=supabaseAdmin();
  const {data:existing,error:readError}=await sb.from('wallet_accounts').select('id,wallet_type,provider,address,chain_id,status,provider_wallet_id').eq('user_id',user.id).in('status',['provisioning','active']).order('created_at',{ascending:false}).limit(1).maybeSingle();
  if(readError)throw new Error(readError.message);
  if(existing)return existing;
  if(!config.gates.walletProvisioning)return null;
  const created=await provisionEmbeddedWallet({userId:user.id,email:user.email});
  const row={user_id:user.id,wallet_type:'embedded',provider:created.provider,address:normalizeAddress(created.address),chain_id:config.chain.id,status:'active',provider_wallet_id:created.providerWalletId};
  const {data,error}=await sb.from('wallet_accounts').insert(row).select().single();
  if(error){
    const {data:retry,retryError}=await sb.from('wallet_accounts').select('id,wallet_type,provider,address,chain_id,status,provider_wallet_id').eq('user_id',user.id).in('status',['provisioning','active']).order('created_at',{ascending:false}).limit(1).maybeSingle();
    if(retryError||!retry)throw new Error(error.message);
    return retry;
  }
  return data;
}
app.get('/api/wallet/summary',async(req,res,next)=>{try{const sb=supabaseAdmin();const w=await getOrCreateEmbeddedWallet(req.user);let balance={};if(w){const {data:b,error:berr}=await sb.from('wallet_balances').select('symbol,decimals,available_atomic,locked_atomic,pending_atomic').eq('wallet_id',w.id).limit(1).maybeSingle();if(berr)throw new Error(berr.message);if(b){const d=10**Number(b.decimals||0);balance={symbol:b.symbol,decimals:b.decimals,availableAtomic:String(b.available_atomic),lockedAtomic:String(b.locked_atomic),pendingAtomic:String(b.pending_atomic),availableFormatted:String(Number(b.available_atomic)/d),lockedFormatted:String(Number(b.locked_atomic)/d),pendingFormatted:String(Number(b.pending_atomic)/d)}}}const data={wallet:w?{id:w.id,type:w.wallet_type,provider:w.provider,address:w.address,chainId:w.chain_id,status:w.status}:null,balance};if(w?.address&&config.chain.rpcUrl&&config.chain.stablecoinAddress){try{data.onchainAtomic=(await tokenBalance(w.address)).toString()}catch{}}res.json(data)}catch(e){next(e)}});
app.post('/api/wallet/provision',async(req,res,next)=>{try{const wallet=await getOrCreateEmbeddedWallet(req.user);if(!wallet)return res.status(409).json({error:'wallet_provisioning_disabled'});res.json({wallet})}catch(e){next(e)}});
app.post('/api/wallet/link-external',async(req,res,next)=>{try{const address=normalizeAddress(req.body.address);const chainId=Number(req.body.chainId);if(chainId!==config.chain.id)return res.status(409).json({error:'wrong_chain',expectedChainId:config.chain.id});const sb=supabaseAdmin();const {data,error}=await sb.from('wallet_accounts').upsert({user_id:req.user.id,wallet_type:'external',provider:'eip1193',address,chain_id:chainId,status:'active'},{onConflict:'chain_id,address'}).select().single();if(error)throw new Error(error.message);res.json({wallet:data})}catch(e){next(e)}});
app.post('/api/wallet/withdraw',async(req,res,next)=>{try{if(!config.gates.withdrawals)return res.status(409).json({error:'withdrawals_disabled'});const destination=normalizeAddress(req.body.destination);const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'invalid_amount'});const sb=supabaseAdmin();const {data:w}=await sb.from('wallet_accounts').select('id,wallet_type').eq('user_id',req.user.id).eq('status','active').order('created_at',{ascending:false}).limit(1).maybeSingle();if(!w)return res.status(409).json({error:'wallet_not_ready'});const amountAtomic=BigInt(Math.round(amount*10**config.chain.stablecoinDecimals));const {data,error}=await sb.from('wallet_withdrawals').insert({user_id:req.user.id,wallet_id:w.id,chain_id:config.chain.id,token_address:config.chain.stablecoinAddress,destination_address:destination,amount_atomic:amountAtomic.toString(),status:'requested'}).select().single();if(error)throw new Error(error.message);if(w.wallet_type==='embedded')await requestEmbeddedTransfer({withdrawal:data}).catch(()=>{});res.status(202).json(data)}catch(e){next(e)}});

app.post('/api/matchmaking/join',async(req,res,next)=>{try{const amount=Number(req.body.entryAmount||0);if(amount>0)return res.status(409).json({error:'use_paid_entry_prepare_flow'});const result=await joinMatch({userId:req.user.id,gameSlug:req.body.gameSlug,region:req.body.region||'global'});res.json(result)}catch(e){next(e)}});
app.post('/api/matchmaking/prepare-paid-entry',async(req,res,next)=>{try{if(!config.gates.cashMode||!config.gates.paidMatchmaking)return res.status(409).json({error:'paid_matchmaking_disabled'});const gameSlug=String(req.body.gameSlug||''),region=String(req.body.region||'global'),walletAddress=normalizeAddress(req.body.walletAddress),entryAmount=Number(req.body.entryAmount);if(!Number.isFinite(entryAmount)||entryAmount<=0)return res.status(400).json({error:'invalid_entry_amount'});const entryAmountAtomic=BigInt(Math.round(entryAmount*10**config.chain.stablecoinDecimals));const ttlSeconds=300;const sb=supabaseAdmin();const {data:prepared,error}=await sb.rpc('prepare_paid_match',{p_user_id:req.user.id,p_game_slug:gameSlug,p_region:region,p_wallet_address:walletAddress,p_entry_amount_atomic:entryAmountAtomic.toString(),p_currency:config.chain.stablecoinSymbol,p_chain_id:config.chain.id,p_token_address:config.chain.stablecoinAddress,p_escrow_address:config.chain.escrowAddress,p_ttl_seconds:ttlSeconds});if(error)throw new Error(error.message);const joinDeadline=Math.floor(Date.now()/1000)+ttlSeconds;if(prepared.created_match)await createEscrowMatch({matchId:prepared.match_id,entryAmountAtomic,maxPlayers:12,joinDeadline});res.json({...prepared,chainId:config.chain.id,tokenAddress:config.chain.stablecoinAddress,escrowAddress:config.chain.escrowAddress,entryAmountAtomic:entryAmountAtomic.toString(),transactions:buildEntryTransactions({matchId:prepared.match_id,entryAmountAtomic,from:walletAddress})})}catch(e){next(e)}});
app.post('/api/matchmaking/confirm-paid-entry',async(req,res,next)=>{try{const reservationId=String(req.body.reservationId||''),matchId=String(req.body.matchId||''),txHash=String(req.body.txHash||''),walletAddress=normalizeAddress(req.body.walletAddress);if(!reservationId||!matchId||!txHash)return res.status(400).json({error:'missing_confirmation_fields'});const sb=supabaseAdmin();const {data:r,error}=await sb.from('entry_reservations').select('id,user_id,entry_amount_atomic,match_id,status').eq('id',reservationId).eq('user_id',req.user.id).maybeSingle();if(error||!r)return res.status(404).json({error:'reservation_not_found'});if(r.match_id!==matchId||r.status!=='quoted')return res.status(409).json({error:'reservation_not_confirmable'});const verified=await verifyEntryLocked({txHash,matchId,player:walletAddress,expectedAmountAtomic:r.entry_amount_atomic});const {data:joined,error:confirmError}=await sb.rpc('confirm_paid_entry',{p_reservation_id:reservationId,p_tx_hash:txHash,p_event_index:verified.logIndex});if(confirmError)throw new Error(confirmError.message);res.json({...joined,verified})}catch(e){next(e)}});
app.post('/api/matchmaking/leave',async(req,res,next)=>{try{res.json(await leaveMatch({userId:req.user.id,matchId:req.body.matchId}))}catch(e){next(e)}});
app.post('/api/matchmaking/ticket',async(req,res,next)=>{try{const t=await issueServerTicket({userId:req.user.id,matchId:req.body.matchId});res.json({...t,websocketUrl:process.env.WEBSOCKET_PUBLIC_URL||''})}catch(e){next(e)}});

app.use((err,_req,res,_next)=>{const status=err.status||500;if(status>=500)console.error(err);res.status(status).json({error:err.message||'server_error'})});

const server=http.createServer(app);const wss=new WebSocketServer({noServer:true});const rooms=new Map();
server.on('upgrade',async(req,socket,head)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname!=='/ws')return socket.destroy();const raw=u.searchParams.get('ticket');if(!raw)return socket.destroy();const t=await consumeServerTicket(raw);wss.handleUpgrade(req,socket,head,ws=>{ws.skill={matchId:t.match_id,userId:t.user_id,alive:true};wss.emit('connection',ws,req)})}catch{socket.destroy()}});
wss.on('connection',ws=>{const {matchId,userId}=ws.skill;if(!rooms.has(matchId))rooms.set(matchId,new Set());const room=rooms.get(matchId);room.add(ws);broadcast(room,{type:'presence',userId,state:'connected'});ws.send(JSON.stringify({type:'welcome',matchId,userId,protocol:'skill-arcade-v1'}));ws.on('message',buf=>{let m;try{m=JSON.parse(String(buf))}catch{return}if(m.type==='ping')return ws.send(JSON.stringify({type:'pong',t:m.t||Date.now()}));if(m.type==='ready')return broadcast(room,{type:'ready',userId});if(m.type==='input'){const input=sanitizeInput(m);if(input)broadcast(room,{type:'input',userId,seq:input.seq,input:input.input})}});ws.on('close',()=>{room.delete(ws);broadcast(room,{type:'presence',userId,state:'disconnected'});if(!room.size)rooms.delete(matchId)})});
function sanitizeInput(m){const x=Number(m.input?.x),y=Number(m.input?.y),seq=Number(m.seq);if(!Number.isInteger(seq)||!Number.isFinite(x)||!Number.isFinite(y))return null;return {seq,input:{x:Math.max(-1,Math.min(1,x)),y:Math.max(-1,Math.min(1,y)),jump:!!m.input?.jump,dash:!!m.input?.dash,fire:!!m.input?.fire}}}
function broadcast(room,msg){const s=JSON.stringify(msg);for(const c of room)if(c.readyState===1)c.send(s)}
server.listen(config.port,()=>console.log(`Skill Arcade live server listening on :${config.port}`));
