(()=>{
'use strict';
const cfg=window.SKILL_ARCADE_LIVE_CONFIG||{},online=window.SKILL_ARCADE_ONLINE_CONFIG||{};
let sb=null,session=null,wallet=null,summary=null,remote=null,game=null,tier=(cfg.matchmaking?.entryTiers||[1])[0];
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const apiReady=()=>!!cfg.apiBaseUrl,sbReady=()=>!!(online.supabaseUrl&&online.supabaseAnonKey&&window.supabase?.createClient);
const chain=()=>{const r=remote?.chain||{};return {...(cfg.chain||{}),chainId:r.id??cfg.chain?.chainId,networkName:r.networkName||cfg.chain?.networkName,stablecoin:{...(cfg.chain?.stablecoin||{}),symbol:r.stablecoinSymbol||cfg.chain?.stablecoin?.symbol,decimals:r.stablecoinDecimals??cfg.chain?.stablecoin?.decimals,address:r.stablecoinAddress??cfg.chain?.stablecoin?.address},escrowContractAddress:r.escrowAddress??cfg.chain?.escrowContractAddress}};
const chainReady=()=>!!(chain().chainId&&chain().stablecoin?.address&&chain().escrowContractAddress),gate=k=>!!(remote?.gates?.[k]??cfg.gates?.[k]);
function supa(){if(!sb&&sbReady())sb=window.supabase.createClient(online.supabaseUrl,online.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true}});return sb}
async function refreshSession(){const c=supa();if(!c)return session=null;session=(await c.auth.getSession()).data.session||null;return session}
async function token(){return (await refreshSession())?.access_token||''}
async function api(path,opt={}){if(!apiReady())throw Error('Live API is not connected yet.');const t=await token(),r=await fetch(String(cfg.apiBaseUrl).replace(/\/$/,'')+path,{...opt,headers:{'content-type':'application/json',...(t?{authorization:'Bearer '+t}:{}),...(opt.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||d.message||('API '+r.status));return d}
function state(){if(!sbReady())return'CONNECT SUPABASE';if(!apiReady())return'DEPLOY API';if(!chainReady())return'CONNECT CRYPTO';return gate('cashMode')?'LIVE':'TESTNET / LOCKED'}
function row(n,ok){return `<div><b>${ok?'✓':'·'}</b><span>${esc(n)}</span><em class="${ok?'ok':''}">${ok?'READY':'SETUP'}</em></div>`}
function walletPanel(){const c=chain(),b=summary||{};return `<section class="live-wallet-panel" id="liveWalletPanel"><div class="live-wallet-head"><div><div class="eyebrow">REAL WALLET INFRASTRUCTURE</div><h2>Platform wallet</h2><p>Embedded or external EVM wallet. Skill Arcade never stores your private key.</p></div><span class="live-wallet-state">${state()}</span></div><div class="live-wallet-grid"><article><span>Wallet</span><b id="liveWalletAddress">${esc(wallet?.address?wallet.address.slice(0,6)+'…'+wallet.address.slice(-4):'Not created')}</b></article><article><span>Available</span><b>${esc(b.availableFormatted??'—')} ${esc(c.stablecoin?.symbol||'USDC')}</b></article><article><span>In matches</span><b>${esc(b.lockedFormatted??'—')} ${esc(c.stablecoin?.symbol||'USDC')}</b></article><article><span>Pending</span><b>${esc(b.pendingFormatted??'—')} ${esc(c.stablecoin?.symbol||'USDC')}</b></article></div><div class="live-wallet-actions"><button class="primary" id="liveCreateWallet">Create platform wallet</button><button id="liveConnectWallet">Connect external wallet</button><button id="liveDeposit" ${gate('deposits')?'':'disabled'}>Deposit</button><button id="liveWithdraw" ${gate('withdrawals')?'':'disabled'}>Withdraw</button><button id="liveRefresh">Refresh</button></div><div class="live-setup-list">${row('Account / Supabase',sbReady())}${row('Live API / match server',apiReady())}${row('Embedded wallet provider',cfg.wallet?.embeddedProvider&&cfg.wallet.embeddedProvider!=='unconfigured')}${row((c.networkName||'EVM chain')+' + '+(c.stablecoin?.symbol||'stablecoin'),chainReady())}${row('Escrow + paid matchmaking',gate('paidMatchmaking')&&gate('cashMode'))}</div><p id="liveWalletMessage" class="live-note">Connect providers later; all money gates start locked.</p></section>`}
function mountWallet(){const t=document.querySelector('[data-panel="wallet"]');if(!t)return;t.classList.add('live-infra-mounted');$('liveWalletPanel')?.remove();t.insertAdjacentHTML('afterbegin',walletPanel());$('liveCreateWallet').onclick=provision;$('liveConnectWallet').onclick=connectExternal;$('liveDeposit').onclick=deposit;$('liveWithdraw').onclick=withdraw;$('liveRefresh').onclick=loadSummary}
function msg(s,bad=false){const n=$('liveWalletMessage');if(n){n.textContent=s;n.className='live-note '+(bad?'live-error':'')}}
async function provision(){if(!await refreshSession()){document.getElementById('onlineAccountBtn')?.click();return msg('Log in first.',true)}if(!gate('walletProvisioning'))return msg('Wallet provisioning is wired but locked until you configure the provider.',true);try{const d=await api('/api/wallet/provision',{method:'POST',body:'{}'});wallet=d.wallet||d;mountWallet()}catch(e){msg(e.message,true)}}
async function connectExternal(){if(!window.ethereum)return msg('No external EVM wallet found.',true);try{const a=(await ethereum.request({method:'eth_requestAccounts'}))[0],cid=parseInt(await ethereum.request({method:'eth_chainId'}),16);wallet={type:'external',address:a,chainId:cid};if(apiReady()&&session)await api('/api/wallet/link-external',{method:'POST',body:JSON.stringify({address:a,chainId:cid})});mountWallet()}catch(e){msg(e.message,true)}}
async function loadSummary(){if(!await refreshSession())return msg('Log in first.',true);try{const d=await api('/api/wallet/summary');wallet=d.wallet||wallet;summary=d.balance||{};mountWallet()}catch(e){msg(e.message,true)}}
function modals(){if($('liveMatchModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="liveDepositModal" class="modal-backdrop hidden"><section class="info-modal"><button class="close-btn" data-live-close="liveDepositModal">×</button><div class="eyebrow">FUND YOUR WALLET</div><h2>Deposit</h2><div id="liveDepositAddress" class="live-deposit-address">Wallet not ready</div><p class="live-note">Only send the configured stablecoin on the configured network.</p></section></div><div id="liveWithdrawModal" class="modal-backdrop hidden"><section class="info-modal"><button class="close-btn" data-live-close="liveWithdrawModal">×</button><div class="eyebrow">WITHDRAW</div><h2>Send to your wallet</h2><label class="form-field"><span>Destination</span><input id="liveWithdrawAddress" placeholder="0x…"></label><label class="form-field"><span>Amount</span><input id="liveWithdrawAmount" type="number" min="0" step=".01"></label><button id="liveWithdrawSubmit" class="launch-btn">REQUEST WITHDRAWAL</button><p id="liveWithdrawMessage" class="live-note"></p></section></div><div id="liveMatchModal" class="modal-backdrop hidden"><section class="info-modal"><button class="close-btn" data-live-close="liveMatchModal">×</button><div class="eyebrow">REAL MATCH INFRASTRUCTURE</div><h2 id="liveMatchTitle">Join match</h2><p class="modal-copy">12 real players · server lobby · escrow-funded entry when cash mode is enabled.</p><div id="liveTierList" class="live-modal-grid"></div><div id="liveMatchChecks" class="live-setup-list"></div><button id="liveJoinMatch" class="launch-btn">JOIN FREE REAL QUEUE</button><p id="liveMatchMessage" class="live-note"></p></section></div>`);document.querySelectorAll('[data-live-close]').forEach(b=>b.onclick=()=>$(b.dataset.liveClose)?.classList.add('hidden'));$('liveWithdrawSubmit').onclick=submitWithdraw;$('liveJoinMatch').onclick=join}
function deposit(){modals();if(!wallet?.address)return msg('Create/connect a wallet first.',true);$('liveDepositAddress').textContent=wallet.address;$('liveDepositModal').classList.remove('hidden')}
function withdraw(){modals();$('liveWithdrawModal').classList.remove('hidden')}
async function submitWithdraw(){const n=$('liveWithdrawMessage');if(!gate('withdrawals'))return n.textContent='Withdrawals are locked.';try{const d=await api('/api/wallet/withdraw',{method:'POST',body:JSON.stringify({destination:$('liveWithdrawAddress').value.trim(),amount:+$('liveWithdrawAmount').value})});n.textContent='Withdrawal request '+(d.id||'created')}catch(e){n.textContent=e.message}}
function decorate(){document.querySelectorAll('[data-open-game]').forEach(p=>{const card=p.closest('.game-card'),a=p.closest('.card-actions');if(!card||!a||card.querySelector('[data-live-game]'))return;const b=document.createElement('button');b.className='live-match-action';b.dataset.liveGame=p.dataset.openGame;b.innerHTML='<span class="live-match-badge">LIVE</span> REAL MATCH';b.onclick=()=>openMatch(p.dataset.openGame);a.insertAdjacentElement('afterend',b)})}
function checks(){const paid=gate('paidMatchmaking')&&gate('cashMode'),n=$('liveMatchChecks');if(!n)return;n.innerHTML=(paid?[['Logged-in account',!!session],['Wallet',!!wallet?.address],['API',apiReady()],['Chain + escrow',chainReady()],['Paid matchmaking',true]]:[['Logged-in account',!!session],['API + match server',apiReady()],['Real 12-player queue',true],['Crypto entry mode',false]]).map(x=>row(...x)).join('');$('liveJoinMatch').textContent=paid?'FUND ENTRY & JOIN':'JOIN FREE REAL QUEUE'}
function tiers(){const c=chain(),n=$('liveTierList');n.innerHTML=(cfg.matchmaking?.entryTiers||[1,5,20]).map(v=>`<button class="live-tier ${+v===+tier?'active':''}" data-tier="${v}"><strong>${v} ${esc(c.stablecoin?.symbol||'USDC')}</strong><span>12-player entry tier</span></button>`).join('');n.querySelectorAll('[data-tier]').forEach(b=>b.onclick=()=>{tier=+b.dataset.tier;tiers()})}
async function openMatch(slug){modals();game=slug;tier=(cfg.matchmaking?.entryTiers||[1])[0];$('liveMatchTitle').textContent=(document.querySelector(`[data-open-game="${CSS.escape(slug)}"]`)?.closest('.game-card')?.querySelector('h2')?.textContent||slug)+' · real match';tiers();await refreshSession();checks();$('liveMatchModal').classList.remove('hidden')}
async function ensureChain(){if(wallet?.type!=='external'||!window.ethereum)return;const c=chain(),now=parseInt(await ethereum.request({method:'eth_chainId'}),16);if(now!==Number(c.chainId))await ethereum.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x'+Number(c.chainId).toString(16)}]})}
async function sendTx(tx){if(wallet?.type==='external'){await ensureChain();return ethereum.request({method:'eth_sendTransaction',params:[tx]})}const a=window.SkillArcadeEmbeddedWallet;if(a?.sendTransaction){const r=await a.sendTransaction(tx);return typeof r==='string'?r:r?.hash}throw Error('Embedded wallet transaction adapter is not connected yet.')}
async function join(){const n=$('liveMatchMessage');n.className='live-note';await refreshSession();checks();if(!session)return n.textContent='Log in first.';try{const paid=gate('paidMatchmaking')&&gate('cashMode');if(!paid){const d=await api('/api/matchmaking/join',{method:'POST',body:JSON.stringify({gameSlug:game,entryAmount:0})});n.textContent=`Real queue joined · ${d.match_id||d.matchId} · ${d.players||1}/${d.target_players||12}`;n.classList.add('live-success');return}if(!wallet?.address||!chainReady())throw Error('Wallet/chain/escrow setup is incomplete.');const p=await api('/api/matchmaking/prepare-paid-entry',{method:'POST',body:JSON.stringify({gameSlug:game,entryAmount:tier,walletAddress:wallet.address})});let hash='';for(const tx of p.transactions||[]){const h=await sendTx(tx);if(tx.kind==='join')hash=h}if(!hash)throw Error('Escrow join transaction missing.');const d=await api('/api/matchmaking/confirm-paid-entry',{method:'POST',body:JSON.stringify({reservationId:p.reservation_id,matchId:p.match_id,txHash:hash,walletAddress:wallet.address})});n.textContent=`Funded queue joined · ${d.players||1}/${d.target_players||12}`;n.classList.add('live-success')}catch(e){n.textContent=e.message;n.classList.add('live-error')}}
async function boot(){if(apiReady())try{remote=await (await fetch(String(cfg.apiBaseUrl).replace(/\/$/,'')+'/api/config')).json()}catch{};const target=document.querySelector('.arcade-beta-strip')||document.querySelector('[data-panel="games"] .page-head>div');if(target&&!$('liveInfraBadge')){const b=document.createElement('span');b.id='liveInfraBadge';b.className='live-infra-badge'+(apiReady()&&sbReady()?' ready':'');b.innerHTML='<i></i><span>'+state()+'</span>';target.appendChild(b)}mountWallet();modals();decorate();await refreshSession();if(session&&apiReady())await loadSummary().catch(()=>{});new MutationObserver(decorate).observe(document.documentElement,{subtree:true,childList:true})}
window.SkillArcadeLive={connectExternal,provision,loadSummary};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();