(()=>{
'use strict';
const STORAGE_KEY='skillArcadeDemoAccountV1', CONTROL_KEY='skillArcadeDemoControlsV2', DISPUTE_KEY='skillArcadeDemoDisputesV1', SESSION_KEY='skillArcadeSessionStartV1';
const DEFAULT_BALANCE=25,FEE_RATE=.05,tiers=[1,5,20];
const GAMES={
'floor-breaker':{name:'Floor Breaker',no:'01',maps:1,category:'SURVIVAL',players:24,time:'~5 min',rule:'Break the floor. Stay out of the lava.',controls:'WASD + mouse · click to fire · Space to jump',win:'Last survivor wins. If time expires, remaining players rank by blocks destroyed.',path:'games/floor-breaker/index.html',ratios:[12,6.8,4],thumb:'assets/thumbnails/floor-breaker.svg'},
'obstacle-sprint':{name:'Obstacle Sprint',no:'02',maps:999,category:'RACE',players:24,time:'~4–5 min',rule:'Race the obstacle course. First three finishers place.',controls:'WASD to move · Space to jump',win:'First three players across the finish line take the podium.',path:'games/obstacle-sprint/index.html',ratios:[12,6.8,4],thumb:'assets/thumbnails/obstacle-sprint.svg'},
'knockout':{name:'Knockout',no:'03',maps:1,category:'ARENA',players:24,time:'Last survivor',rule:'Dash into players and launch them off the arena.',controls:'WASD to move · Space to dash',win:'Survive longest. Elimination order determines placement.',path:'games/knockout/index.html',ratios:[12,6.8,4],thumb:'assets/thumbnails/knockout.svg'},
'bomb-tag':{name:'Bomb Tag',no:'04',maps:1,category:'TAG',players:24,time:'Last survivor',rule:'Pass the bomb before the timer reaches zero.',controls:'WASD to move · Space to dash · touch a player to pass',win:'Do not hold the bomb when it explodes. Last survivor wins.',path:'games/bomb-tag/index.html',ratios:[12,6.8,4],thumb:'assets/thumbnails/bomb-tag.svg'},
'falling-tiles':{name:'Falling Tiles',no:'05',maps:999,category:'SURVIVAL',players:24,time:'Last survivor',rule:'Every tile you step on disappears. Keep moving.',controls:'WASD to move',win:'Last survivor wins. Falling order determines the rest.',path:'games/falling-tiles/index.html',ratios:[12,6.8,4],thumb:'assets/thumbnails/falling-tiles.svg'},
'red-light-run':{name:'Red Light Run',no:'06',maps:1,category:'REACTION',players:24,time:'~95 sec',rule:'Run on green. Freeze on red. Reach the finish first.',controls:'WASD to move',win:'First three finishers place. Moving on red sends you back.',path:'games/red-light-run/index.html',ratios:[12,6.8,4],thumb:'assets/thumbnails/red-light-run.svg'},
'coin-rush':{name:'Coin Rush',no:'07',maps:1,category:'SCORE',players:24,time:'90 sec',rule:'Collect more coins than everyone else before time runs out.',controls:'WASD to move · Space to dash',win:'Highest score when the round ends takes first place.',path:'games/coin-rush/index.html',ratios:[12,6.8,4],thumb:'assets/thumbnails/coin-rush.svg'},
'safe-zone':{name:'Safe Zone',no:'08',maps:4,category:'SURVIVAL',players:24,time:'Last survivor',rule:'Reach the highlighted zone before the other platforms drop.',controls:'WASD to move',win:'Wrong platform drops. Rounds accelerate until one survivor remains.',path:'games/safe-zone/index.html',ratios:[12,6.8,4],thumb:'assets/thumbnails/safe-zone.svg'},
'wall-dodge':{name:'Wall Dodge',no:'09',maps:4,category:'REACTION',players:24,time:'Last survivor',rule:'Fit through the moving gap. Four hits and you are out.',controls:'WASD to move',win:'Walls get faster and tighter until one survivor remains.',path:'games/wall-dodge/index.html',ratios:[12,6.8,4],thumb:'assets/thumbnails/wall-dodge.svg'},
'maze-rush':{name:'Maze Rush',no:'10',maps:999,category:'RACE',players:24,time:'~4–5 min',rule:'Find the exit. First three players out place.',controls:'WASD to move',win:'First three players through the exit take the podium.',path:'games/maze-rush/index.html',ratios:[12,6.8,4],thumb:'assets/thumbnails/maze-rush.svg'},
'meteor-dodge':{name:'Meteor Dodge',no:'11',maps:4,category:'SURVIVAL',players:24,time:'Last survivor',rule:'Escape the warning circles. Four hits and you are out.',controls:'WASD to move',win:'Strikes accelerate until only one survivor remains.',path:'games/meteor-dodge/index.html',ratios:[12,6.8,4],thumb:'assets/thumbnails/meteor-dodge.svg'}
};
const TOKEN_SYMBOL=String(window.SKILL_ARCADE_LIVE_CONFIG?.chain?.stablecoin?.symbol||'USDC').toUpperCase();
const $=id=>document.getElementById(id), money=v=>`${Math.max(0,+v||0).toFixed(2)} ${TOKEN_SYMBOL}`, signed=v=>`${(+v||0)>=0?'+':'-'}${Math.abs(+v||0).toFixed(2)} ${TOKEN_SYMBOL}`;
const fallbackAccount=()=>({wallet:DEFAULT_BALANCE,totalPrizes:0,wins:0,totalMatches:0,matches:[],profile:{username:'Demo Player',region:'',onboarded:false}});
function loadJSON(key,fallback){try{const r=localStorage.getItem(key);return r?{...fallback,...JSON.parse(r)}:{...fallback}}catch{return{...fallback}}}
function loadAccount(){const f=fallbackAccount(),d=loadJSON(STORAGE_KEY,f);return{...f,...d,wallet:Number.isFinite(+d.wallet)?Math.max(0,+d.wallet):DEFAULT_BALANCE,totalPrizes:Number.isFinite(+d.totalPrizes)?Math.max(0,+d.totalPrizes):0,wins:Number.isFinite(+d.wins)?Math.max(0,+d.wins):0,totalMatches:Number.isFinite(+d.totalMatches)?Math.max(0,+d.totalMatches):0,matches:Array.isArray(d.matches)?d.matches:[],profile:{...f.profile,...(d.profile||{})}}}
function controlDefaults(){return{dailyLimit:25,dailySpent:0,dailyDate:new Date().toISOString().slice(0,10),reminder:30,pausedUntil:0,eligibility:{age:false,identity:false,location:false,fair:false}}}
function loadControls(){let c=loadJSON(CONTROL_KEY,controlDefaults());const today=new Date().toISOString().slice(0,10);if(c.dailyDate!==today){c.dailyDate=today;c.dailySpent=0}c.eligibility={...controlDefaults().eligibility,...(c.eligibility||{})};return c}
function saveControls(){localStorage.setItem(CONTROL_KEY,JSON.stringify(controls))}
function loadDisputes(){try{const d=JSON.parse(localStorage.getItem(DISPUTE_KEY)||'[]');return Array.isArray(d)?d:[]}catch{return[]}}
function saveDisputes(){localStorage.setItem(DISPUTE_KEY,JSON.stringify(disputes))}
let account=loadAccount(),controls=loadControls(),disputes=loadDisputes(),selectedGame='floor-breaker',selectedEntry=1,currentFilter='ALL',currentReceiptIndex=null,queueTimer=null,queueCancelled=false;
if(!sessionStorage.getItem(SESSION_KEY))sessionStorage.setItem(SESSION_KEY,String(Date.now()));

const POLICIES={
terms:{title:'Draft Terms of Service',body:`<p>This prototype demonstrates the intended product flow only. No real-money service is offered.</p><h3>Proposed live principles</h3><ul><li>Only eligible adults in approved jurisdictions may access cash competitions.</li><li>Players must provide accurate account and identity information.</li><li>One person, one account. Multi-accounting, collusion and cheating are prohibited.</li><li>Game outcomes are determined by the published rules for each title.</li><li>Final terms, governing law, dispute process and payment terms require counsel approval.</li></ul>`},
competition:{title:'Draft Competition Rules',body:`<p>Every lobby shows its entry amount, number of players, prize pool, platform fee and top-three prizes before entry.</p><ul><li>All players in a lobby receive the same game version and gameplay rules.</li><li>Only published skill mechanics determine placement.</li><li>Top three placements receive the displayed prizes unless the specific game rules state a no-contest outcome.</li><li>A player who voluntarily leaves after a match begins normally forfeits the entry and receives the placement produced by the game rules.</li><li>Server-authoritative event logs would be the official live record.</li></ul>`},
refund:{title:'Draft Disconnect & Refund Policy',body:`<h3>Before the match starts</h3><p>Players can cancel matchmaking before the lobby locks with no entry charged.</p><h3>After the match starts</h3><ul><li>Voluntary disconnect: normally treated as a loss/forfeit.</li><li>Verified platform-wide server failure before a meaningful result can be produced: proposed automatic entry refund.</li><li>Partial outage affecting only some players: result placed into review before settlement.</li><li>Suspected cheating or data corruption: settlement may be held pending integrity review.</li></ul><p>These are draft rules for counsel review, not final commitments.</p>`},
fairplay:{title:'Draft Fair Play Policy',body:`<ul><li>Authoritative game server decides positions, collisions, eliminations and final results.</li><li>Client inputs are validated; clients do not write their own balances or placements.</li><li>Device/session risk checks, bot detection, impossible-movement checks, replay/event logs and collusion analysis are proposed for live mode.</li><li>Game versions are locked per match and every result receives a match ID.</li><li>Flagged matches can pause settlement and enter manual review.</li></ul>`},
responsible:{title:'Draft Responsible Play Policy',body:`<ul><li>18+ only for proposed real-money competitive access.</li><li>Players can set competition spending limits and session reminders.</li><li>Players can pause competitive access while retaining free practice access.</li><li>Longer self-exclusion and support pathways should be implemented before launch if required or recommended by counsel.</li><li>No credit, lending or chasing-loss prompts should be used.</li></ul>`},
privacy:{title:'Draft Privacy Notice',body:`<p>The live product may need to process account data, identity/KYC results, location eligibility, device security signals, gameplay inputs, match records, wallet transactions and support disputes.</p><ul><li>Collect only what is necessary for eligibility, payments, fair play and support.</li><li>Payment/KYC providers should retain sensitive data where possible instead of duplicating it.</li><li>Retention periods, international transfers, user rights and lawful bases require jurisdiction-specific legal drafting.</li></ul>`}
};

function matchId(index,m){const seq=Math.max(1,(account.totalMatches||account.matches.length)-index);const code=(m.game||'game').split('-').map(x=>x[0]).join('').toUpperCase().slice(0,3);return `SA-${code}-${String(seq).padStart(6,'0')}`}
function gameCard(key,g){return `<article class="game-card" data-category="${g.category}"><div class="game-thumb"><img src="${g.thumb}" alt="${g.name} thumbnail"><div class="thumb-badges"><span>GAME ${g.no}</span><span>${g.category}</span></div></div><div class="game-body"><h2>${g.name}</h2><p>${g.rule}</p><div class="game-meta"><span>${g.players} players</span><span>${g.time}</span><span>Podium · top 3</span><span>${g.maps>1?g.maps+' maps':'Signature arena'}</span></div><div class="card-actions"><button type="button" class="ghost-btn" data-rules-game="${key}">RULES</button><button type="button" class="play-btn" data-open-game="${key}">PLAY</button></div></div></article>`}
function renderGames(){const grid=$('gameGrid');grid.innerHTML=Object.entries(GAMES).filter(([,g])=>currentFilter==='ALL'||g.category===currentFilter).map(([k,g])=>gameCard(k,g)).join('');grid.querySelectorAll('[data-open-game]').forEach(b=>b.onclick=()=>openLobby(b.dataset.openGame));grid.querySelectorAll('[data-rules-game]').forEach(b=>b.onclick=()=>openRules(b.dataset.rulesGame));$('gameCount').textContent=`${Object.keys(GAMES).length} games`}

function refresh(){account=loadAccount();controls=loadControls();disputes=loadDisputes();const pn=account.profile?.username||'Demo Player';$('profileName').textContent=pn;$('profileRegion').textContent=account.profile?.region?`Region: ${account.profile.region} · one profile across every mini-game.`:'One profile across every mini-game.';$('avatarLabel').textContent=pn.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'P1';$('headerBalance').textContent=money(account.wallet);$('walletBalance').textContent=money(account.wallet);$('modalBalance').textContent=money(account.wallet);$('walletAvailable').textContent=money(account.wallet);$('walletMatches').textContent=account.totalMatches||0;$('walletWins').textContent=account.wins||0;$('walletPrizes').textContent=money(account.totalPrizes||0);$('profileMatches').textContent=account.totalMatches||0;$('profileWins').textContent=account.wins||0;renderHistory();renderLedger();renderRanks();renderControls();renderTickets();renderEligibility();updateModal();checkSessionReminder()}
function renderHistory(){const list=$('historyList'),ms=account.matches||[];$('historyPlayed').textContent=`${account.totalMatches||0} played`;if(!ms.length){list.innerHTML='<div class="empty-state">No competitive demo matches yet. Practice matches do not appear here.</div>';return}list.innerHTML=ms.slice(0,50).map((m,i)=>{const name=m.gameName||GAMES[m.game]?.name||'Skill Game',place=m.forfeit?'Left':(`#${m.place||'-'}`),net=+m.net||0,id=matchId(i,m);let detail=m.detail||'';if(m.lobby)detail+=(detail?' · ':'')+`${money(m.lobby)} lobby`;return `<article class="history-row"><div class="history-main"><strong>${name}</strong><span>${id} · ${place}${detail?' · '+detail:''}</span></div><b class="${net>=0?'positive':'negative'}">${signed(net)}</b><div class="row-actions"><button data-receipt="${i}" type="button">Receipt</button><button data-report="${i}" type="button">Report</button></div></article>`}).join('');list.querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>openReceipt(+b.dataset.receipt));list.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>openDispute(+b.dataset.report))}
function renderLedger(){const list=$('ledgerList'),ms=account.matches||[];if(!ms.length){list.innerHTML='<div class="empty-state small">Wallet activity appears after competitive demo matches.</div>';return}const rows=[];ms.slice(0,25).forEach((m,i)=>{const id=matchId(i,m),entry=+m.lobby||1,prize=+m.prize||0;rows.push({label:'Match tier',meta:`${id} · ${m.gameName||GAMES[m.game]?.name||'Game'}`,amount:-entry,status:'Complete'});if(prize>0)rows.push({label:'Podium reward',meta:`${id} · Placement #${m.place||'-'}`,amount:prize,status:'Complete'})});list.innerHTML=rows.map(r=>`<div class="ledger-row"><div><strong>${r.label}</strong><span>${r.meta}</span></div><em>${r.status}</em><b class="${r.amount>=0?'positive':'negative'}">${signed(r.amount)}</b></div>`).join('')}
function renderRanks(){const grid=$('rankGrid');grid.innerHTML=Object.entries(GAMES).map(([key,g])=>{const ms=(account.matches||[]).filter(m=>m.game===key&&!m.forfeit),wins=ms.filter(m=>m.place===1).length,podiums=ms.filter(m=>m.place&&m.place<=3).length,score=ms.length*50+wins*180+podiums*70;let rank='Unranked';if(score>=1200)rank='Diamond';else if(score>=650)rank='Gold';else if(score>=300)rank='Silver';else if(score>=50)rank='Bronze';return `<article><img src="${g.thumb}" alt=""><div><b>${g.name}</b><span>${ms.length} matches · ${wins} wins</span></div><em>${rank}</em></article>`}).join('')}
function renderControls(){$('dailyLimit').value=String(controls.dailyLimit??25);$('sessionReminder').value=String(controls.reminder??30);$('dailySpentText').textContent=`${money(controls.dailySpent||0)} used today`;const left=controls.pausedUntil>Date.now()?Math.ceil((controls.pausedUntil-Date.now())/3600000):0;$('pauseStatus').textContent=left?`Paused · about ${left}h remaining`:'Not active';$('pause24h').disabled=!!left}
function renderTickets(){const list=$('ticketList');if(!disputes.length){list.innerHTML='';return}list.innerHTML=`<div class="subsection-head compact"><div><div class="eyebrow">DEMO TICKETS</div><h2>Support history</h2></div></div>`+disputes.slice(0,10).map(t=>`<article class="ticket-row"><div><b>${t.id}</b><span>${t.matchId} · ${t.reason}</span></div><em>OPEN · DEMO</em></article>`).join('')}
function renderEligibility(){const e=controls.eligibility||{};[['Age','age'],['Identity','identity'],['Location','location'],['Fair','fair']].forEach(([cap,k])=>{const el=$(`elig${cap}`),flow=$(`flow${cap}`);if(el){el.textContent=e[k]?'DEMO PASS':'NOT CHECKED';el.classList.toggle('passed',!!e[k])}if(flow){flow.textContent=e[k]?'PASS':'RUN';flow.classList.toggle('passed',!!e[k])}})}

function setTab(name){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===name));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('walletButton').onclick=()=>setTab('wallet');document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderGames()});

const modal=$('lobbyModal');
function openLobby(key){selectedGame=key;selectedEntry=1;const g=GAMES[key];$('lobbyGameNo').textContent=`GAME ${g.no}`;$('lobbyTitle').textContent=g.name;$('lobbyMeta').textContent=g.rule;$('lobbyFacts').textContent=`${g.players} players · ${g.time} · ${g.maps>1?g.maps+' maps':'signature arena'}`;$('lobbyThumb').style.backgroundImage=`url('${g.thumb}')`;$('lobbyOptions').innerHTML=tiers.map(v=>`<button class="lobby-option ${v===1?'active':''}" type="button" data-entry="${v}"><span>${v} ${TOKEN_SYMBOL}</span><small>MATCH TIER</small></button>`).join('');$('lobbyOptions').querySelectorAll('button').forEach(b=>b.onclick=()=>{selectedEntry=+b.dataset.entry;$('lobbyOptions').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));updateModal()});modal.classList.remove('hidden');updateModal()}
function competitiveBlockReason(){if(controls.pausedUntil>Date.now())return 'Skill matches are paused. Practice is still available.';const lim=+controls.dailyLimit||0;if(lim>0&&(controls.dailySpent||0)+selectedEntry>lim)return `Daily stablecoin limit reached (${money(lim)}). Practice is still available.`;if(account.wallet+1e-9<selectedEntry)return 'Not enough stablecoin balance. Practice is free.';return ''}
function updateModal(){const g=GAMES[selectedGame];if(!g)return;const gross=g.players*selectedEntry,fee=gross*FEE_RATE,pool=gross-fee,p=g.ratios.map(r=>r*selectedEntry);$('grossValue').textContent=money(gross);$('feeValue').textContent=money(fee);$('poolValue').textContent=money(pool);$('p1').textContent=money(p[0]);$('p2').textContent=money(p[1]);$('p3').textContent=money(p[2]);$('launchGame').textContent=`PLAY SKILL MATCH · ${money(selectedEntry)}`;const reason=competitiveBlockReason();$('launchGame').disabled=!!reason;$('lobbyMessage').textContent=reason||'Stablecoin entry is locked only when the match starts. Cancel matchmaking before start with no balance change.'}
$('closeLobby').onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};$('howToPlay').onclick=()=>openRules(selectedGame);$('practiceGame').onclick=()=>startQueue(true);$('launchGame').onclick=()=>startQueue(false);

function openRules(key){selectedGame=key;const g=GAMES[key];$('rulesTitle').textContent=g.name;$('rulesBody').innerHTML=`<div class="rule-hero"><img src="${g.thumb}" alt=""><div><b>${g.rule}</b><span>${g.players} players · ${g.time}</span></div></div><div class="rule-steps"><article><span>CONTROLS</span><b>${g.controls}</b></article><article><span>WIN CONDITION</span><b>${g.win}</b></article><article><span>FAIRNESS</span><b>Same game version and same core tools for every player.</b></article></div>`;$('rulesModal').classList.remove('hidden')}
$('rulesPractice').onclick=()=>{closeModal('rulesModal');modal.classList.add('hidden');startQueue(true)};

function startQueue(practice){const g=GAMES[selectedGame];if(!practice){const reason=competitiveBlockReason();if(reason){updateModal();return}}modal.classList.add('hidden');queueCancelled=false;$('queueModal').classList.remove('hidden');$('cancelQueue').disabled=false;$('queueMode').textContent=practice?'PRACTICE · FREE':'SKILL MATCH · ${TOKEN_SYMBOL}';$('queueTitle').textContent=practice?'Preparing practice':'Finding players';$('queueSubtitle').textContent=practice?'Loading the same game mechanics with no wallet impact.':`1 / ${g.players} joined`;$('queueProgress').style.width=practice?'24%':`${100/g.players}%`;$('queueChecks').innerHTML=practice?'<span>Free practice</span><span>No wallet changes</span><span>No history entry</span>':'<span>${TOKEN_SYMBOL}</span><span>Game rules</span><span>Fair play</span>';
  let found=practice?1:1;let ticks=0;clearInterval(queueTimer);queueTimer=setInterval(()=>{if(queueCancelled){clearInterval(queueTimer);return}ticks++;if(practice){const pct=Math.min(100,24+ticks*28);$('queueProgress').style.width=`${pct}%`;if(pct>=100){clearInterval(queueTimer);navigateToGame(true)}return}found=Math.min(g.players,found+Math.max(1,Math.floor(g.players/4)));$('queueSubtitle').textContent=`${found} / ${g.players} joined`;$('queueProgress').style.width=`${found/g.players*100}%`;if(found>=g.players){clearInterval(queueTimer);$('queueTitle').textContent='Match ready';$('queueSubtitle').textContent='Loading game…';$('cancelQueue').disabled=true;setTimeout(()=>navigateToGame(false),700)}},360)}
function navigateToGame(practice){if(queueCancelled)return;const g=GAMES[selectedGame];if(!practice){controls.dailySpent=(+controls.dailySpent||0)+selectedEntry;saveControls()}const url=`${g.path}?entry=${selectedEntry}&from=arcade&autostart=1${practice?'&practice=1':''}`;location.href=url}
$('cancelQueue').onclick=()=>{queueCancelled=true;clearInterval(queueTimer);$('queueModal').classList.add('hidden');modal.classList.remove('hidden')};

function openReceipt(i){const m=account.matches?.[i];if(!m)return;currentReceiptIndex=i;const g=GAMES[m.game]||{name:m.gameName||'Skill Game'},id=matchId(i,m),entry=+m.lobby||1,prize=+m.prize||0,net=+m.net||prize-entry;$('receiptTitle').textContent=g.name;$('receiptBody').innerHTML=`<div><span>Match ID</span><b>${id}</b></div><div><span>Game</span><b>${g.name}</b></div><div><span>Placement</span><b>${m.forfeit?'Forfeit':`#${m.place||'-'}`}</b></div><div><span>Match tier</span><b>-${money(entry)}</b></div><div><span>Podium reward</span><b>+${money(prize)}</b></div><div class="net"><span>Credit change</span><b class="${net>=0?'positive':'negative'}">${signed(net)}</b></div>${m.mapName?`<div><span>Map</span><b>${m.mapName}</b></div>`:''}<div><span>Game version</span><b>V6.5 beta · locked per match</b></div><div><span>Audit record</span><b>${id}-AUDIT</b></div>`;$('receiptModal').classList.remove('hidden')}
$('receiptReport').onclick=()=>{closeModal('receiptModal');openDispute(currentReceiptIndex)};
function openDispute(index=null){const ms=account.matches||[];$('disputeMatch').innerHTML=ms.length?ms.map((m,i)=>`<option value="${i}" ${i===index?'selected':''}>${matchId(i,m)} · ${m.gameName||GAMES[m.game]?.name||'Game'}</option>`).join(''):'<option value="">No matches available</option>';$('disputeDetails').value='';$('disputeModal').classList.remove('hidden')}
$('openSupport').onclick=()=>openDispute(null);$('submitDispute').onclick=()=>{const i=Number($('disputeMatch').value);if(!Number.isInteger(i)||!account.matches?.[i])return;const id=`TKT-${String(Date.now()).slice(-8)}`,ticket={id,matchId:matchId(i,account.matches[i]),reason:$('disputeReason').value,details:$('disputeDetails').value.trim(),created:new Date().toISOString(),status:'open-demo'};disputes.unshift(ticket);saveDisputes();closeModal('disputeModal');renderTickets();alert(`Demo ticket ${id} created in this browser.`)};

function openPolicy(key){const p=POLICIES[key];if(!p)return;$('policyTitle').textContent=p.title;$('policyBody').innerHTML=p.body;$('policyModal').classList.remove('hidden')}
document.querySelectorAll('[data-policy]').forEach(b=>b.onclick=()=>openPolicy(b.dataset.policy));
function closeModal(id){$(id)?.classList.add('hidden')}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));

$('runEligibility').onclick=()=>{$('eligibilityModal').classList.remove('hidden');renderEligibility()};document.querySelectorAll('[data-elig]').forEach(b=>b.onclick=()=>{const k=b.dataset.elig;controls.eligibility[k]=true;saveControls();renderEligibility()});
$('openFundsFlow').onclick=()=>$('fundsModal').classList.remove('hidden');
$('dailyLimit').onchange=e=>{controls.dailyLimit=+e.target.value;saveControls();renderControls();updateModal()};$('sessionReminder').onchange=e=>{controls.reminder=+e.target.value;saveControls();renderControls()};$('pause24h').onclick=()=>{if(confirm('Pause competitive demo lobbies for 24 hours? Practice will remain available.')){controls.pausedUntil=Date.now()+24*3600000;saveControls();renderControls();updateModal()}};
function checkSessionReminder(){const mins=+controls.reminder||0;if(!mins){$('sessionBanner').classList.add('hidden');return}const start=+sessionStorage.getItem(SESSION_KEY)||Date.now();const dismissed=sessionStorage.getItem('skillArcadeSessionDismissedV1')==='1';if(!dismissed&&Date.now()-start>=mins*60000)$('sessionBanner').classList.remove('hidden')}
$('dismissSession').onclick=()=>{sessionStorage.setItem('skillArcadeSessionDismissedV1','1');$('sessionBanner').classList.add('hidden')};
$('resetDemo').onclick=()=>{if(!confirm('Reset demo wallet, match history, limits and support tickets?'))return;account=fallbackAccount();controls=controlDefaults();disputes=[];localStorage.setItem(STORAGE_KEY,JSON.stringify(account));saveControls();saveDisputes();refresh()};

function maybeOnboard(){if(!account.profile?.onboarded){$('onboardName').value=account.profile?.username||'Demo Player';$('onboardRegion').value=account.profile?.region||'';$('onboardingModal').classList.remove('hidden')}}
$('finishOnboarding').onclick=()=>{const name=$('onboardName').value.trim().slice(0,20)||'Demo Player',region=$('onboardRegion').value.trim().slice(0,40);account.profile={...(account.profile||{}),username:name,region,onboarded:true};localStorage.setItem(STORAGE_KEY,JSON.stringify(account));closeModal('onboardingModal');refresh()};
renderGames();window.addEventListener('focus',refresh);window.addEventListener('pageshow',refresh);refresh();maybeOnboard();
})();
